### ISSUE TITLE
Calls to WebHost.CreateDefaultBuilder override the ASPNETCORE_CONTENTROOT environment variable

### ISSUE THREAD

**Issue by Eilon** [aspnet/Hosting#1335] opened 2018-02-27 00:54 UTC
_From @Matthew-Bonner on February 24, 2018 8:47_

See javiercn's comments:

@Eilon This might be an integration bug. You should be able to change the content root by doing setting the ASPNETCORE_CONTENTROOT environment variable, but I believe that calling UseContentRoot override that.

Hosting just reads the content root from a setting in the host configuration. By default, hosting adds environment variables to the configuration and the call to UseContentRoot adds an in memory collection to the configuration after the environment variables, which I believe it means that value overrides the environment variable.

Given those two things together I think using CreateDefaultBuilder prevents you from using an environment variable to configure the content root, and that can be considered a bug, but I'll leave it to @Tratcher.

Copied from:
https://github.com/aspnet/Home/issues/2897#issuecomment-368148258

_Copied from original issue: aspnet/Home#2901_

**Comment by Eilon** [comment] 2018-02-27 00:54
_From @Matthew-Bonner on February 24, 2018 11:20_

After testing it looks like you don't even need to call UseContentRoot in CreateDefaultBuilder. Can someone confirm this for *nix and mac?

**Comment by glennc** [comment] 2018-03-12 17:41
@davidfowl @DamianEdwards I don't remember why we set content root in CreateDefaultBuilder. I want to say that we did it explicitly, but can't remember in what scenarios it ends up being wrong if we don't. Can either of you?

**Comment by muratg** [comment] 2018-04-20 21:09
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by rducom** [comment] 2018-07-23 10:23
Hi @glennc @muratg 
I have a minimal repro for this issue : https://github.com/rducom/ContentRootRepro/tree/master

This is blocking using WebApplicationFactory in IClassFixture on aspnet core 2.1.2 when the test project is in a /test/ folder

I hope you can reopen the issue.

I didn't manage to find a workaround, so If you have an idea, you're welcome 😃

**Comment by Eilon** [comment] 2018-07-23 16:37
Re-opening so that this can be examined again.

**Comment by Tratcher** [comment] 2018-07-24 14:51
Duplicate of https://github.com/aspnet/MetaPackages/issues/267, fixed in 2.2:
https://github.com/aspnet/MetaPackages/commit/48a9013e089a8d15a3314c83e14679d789fd894d

**Comment by rducom** [comment] 2018-07-25 06:41
Thanks @Tratcher !

**Closed** 2018-07-25 16:29 UTC
