### ISSUE TITLE
 ASP.Net 1.0 Core app - HTTP Error 502.5 - Process Failure in Prod web server but works in Preprod 

### ISSUE THREAD

**Issue by valcs007** [aspnet/Hosting#844] opened 2016-08-25 02:03 UTC
We have an ASP.NET Core 1.0 application which has been successfully deployed and running on our pre-prod server for months.  Today we tried deploying the website to our production server using this article as a guideline:
https://docs.asp.net/en/latest/publishing/iis.html

Bottom line is we’ve tried a bunch of things, but can't get past this error:

```
HTTP Error 502.5 - Process Failure
Common causes of this issue:
* The application process failed to start
* The application process started but then stopped
* The application process started but failed to listen on the configured port
```

How do you go about debugging a 502.5 error, to get to the actual cause of the failure?

The app's log files are getting created, but unfortunately they are empty (0 bytes).  The webserver's Event Viewer contains this entry:
    Process was created with commandline 'D:\Applications\OurAppName\UserInterface.exe' but failed to get the status, errorCode = 0x80070005

Any help would be very much appreciated!

**Comment by cesarbs** [comment] 2016-08-25 05:01
Just to be sure we're on the same page, have you gone through the troubleshooting steps for that error, which you can find in the same page you linked?

**Comment by cesarbs** [comment] 2016-08-25 05:05
Also, 0x80070005 is an access denied error. Could your app be trying to access a resource it does not have permission to in your production server?

**Comment by valcs007** [comment] 2016-08-26 19:33
If it is access denied error, how can we find the actual issue? My stdlogs text files are created in the physical directory of the website but are empty?

I am not sure if empty log files and  "HTTP Error 502.5 - Process Failure" are failing due to the same reason.

System is able to create log files, so i am not sure if its a permission issue

Based on the troubleshooting steps, none of the error matches our scenario. We are running out of ideas on finding the root cause.

Any help would be very much appreciated!

**Comment by GuardRex** [comment] 2016-08-27 02:04
> Based on the troubleshooting steps, none of the error matches our scenario.

That's correct. I didn't provide for access denied. We might be doing that depending on what we find out here.

Is your AppPool identity running under **ApplicationPoolIdentity**?

Can you provide your `project.json`, `web.config`, 'Startup` class, and `Program` class just so we can look things over? Usually a repo works best. You can strip out all of the unimportant bits and mask sensitive values.

**Comment by valcs007** [comment] 2016-08-30 05:52
We are running AppPool identity in Integrated mode under "Network service" . We also tried switching to **ApplicationPoolIdentity** but no luck. 

Since stdlog files are blank, we are not sure which resource is causing Access denied error. I have attached all the requested file.

[Web.config.txt](https://github.com/aspnet/Hosting/files/444088/Web.config.txt)
[Program.cs.txt](https://github.com/aspnet/Hosting/files/444090/Program.cs.txt)
[Project.json.txt](https://github.com/aspnet/Hosting/files/444089/Project.json.txt)
[Startup.cs.txt](https://github.com/aspnet/Hosting/files/444091/Startup.cs.txt)

Thanks,

**Comment by GuardRex** [comment] 2016-08-30 06:04
You should be able to drop the `"imports"` from your tools at this point.

You can drop the `commands` section. That's gone now.

Also, your tools dep versions should be `1.0.0-preview2-final`.

> Since stdlog files are blank

The `web.config` you provided is your unpublished `web.config`. After making the above changes (particularly the the change to the `Microsoft.AspNetCore.Server.IISIntegration.Tools` version), restore, and publish, could you show your published `web.config`?

**Comment by betimd** [comment] 2016-09-14 18:49
Today updated to September Release 1.0.1 and I'm having same issue when I publish in 64bit Windows Server Core 2012 R2 v1.2.0 running IIS 8.5.
Log is telling details like this:

2016-09-14T18:40:53.000Z Error 0:(0) IIS AspNetCore Module - Failed to start process with commandline '"dotnet" .\MySolution.MyApi.dll', ErrorCode = '0x80004005'.
2016-09-14T18:40:53.000Z Warning 0:(0) IIS AspNetCore Module - Warning: Could not create stdoutLogFile \\?\C:\inetpub\AspNetCoreWebApps\app\logs\stdout_2428_2016914184053.log, ErrorCode = -2147024893.

**Comment by danielyewright** [comment] 2016-09-19 13:07
I was experiencing the same issue, and found that I had to explicitly set the path to `dotnet.exe` in the `web.config` for the application to work properly. 

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <!--
    Configure your application settings in appsettings.json. Learn more at https://go.microsoft.com/fwlink/?LinkId=786380
  -->
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="C:\Program Files\dotnet\dotnet.exe" arguments=".\CustomersApp.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />
  </system.webServer>
</configuration>
```

**Comment by valcs007** [comment] 2016-10-11 22:37
Hi GuarRex,

I would like you post some update/questions about this issue.

We had this issue in our Prod web server (Win server 2008 R2, IIS 7). We couldn't resolve this issue. 

**Resolution:**
When we deployed the same code to our new web server (Win server 2012, IIS 8), this issue went away.

Deployment went fine in our pre prod web servers (Win server 2008 R2, IIS 7) with .net core version.
that was released in June.

**Issue:** 

After upgrading our solution to latest .Net core ( All Nuget packages are upgraded) including the Project.Json file( We copied from a new .net core app to ensure it has proper tool/dependency section), deployment failed in our Preprod server (Win server 2008 R2, IIS 7)

**Root Cause**

After analysis and going through various forum, we figured out the "%LAUNCHER_PATH%" variable was never replaced in the published web.config.

**Work Around:**

We replaced "%LAUNCHER_PATH%" variable with our actual executable ( ".\UserInterface.exe") in the web server and everything started working.

**Attachments:**
[Project.json.txt](https://github.com/aspnet/Hosting/files/523106/Project.json.txt)
[Published_Web.config.txt](https://github.com/aspnet/Hosting/files/523107/Published_Web.config.txt)

**Questions:**
1. We were wondering why "%LAUNCHER_PATH%" variable is not being replaced after publising? 

(This was not the issue when we used earlier version of .Net core)
2. To my understanding, the minimum requirement for .Net core app deployment is Win 2008 with IIS 7 
   Do we have any known compatibility issue?
3. Anything to do with Microsoft.AspNetCore.Server.IISIntegration.Tools library version in tools or dependency section?

Thanks,
Valliappan

**Comment by GuardRex** [comment] 2016-10-11 23:04
@valcs007 The `publish iis` tooling (`Microsoft.AspNetCore.Server.IISIntegration.Tools`) should have taken care of updating the `processPath`. Your `tooling` reference and `postpublish` script entries are correct. @moozzyk can comment further on why it might not have been running.

RE: Minimum requirement

2008R2 is IIS 7.5, which is prob what you meant, but yes, that is a supported OS version.

Some had difficulty because the VC++ redist wasn't installed; but currently, the ANCM Hosting bundle installer installs it now when the ANCM is installed (as long as the box has an active Internet connection). Unfortunately, I didn't have the impression that everyone was aware that the installer failed to install it when the box didn't have an Internet connection ... the error was buried in the ANCM Hosting bundle installer log, so it wasn't obvious in several cases that something went wrong. A manual install of the VC++ redist fixes that problem when it occurs.

There are no known compatibility issues. Every case I saw of trouble getting .NET Core apps running on any flavor of WS from 2008R2 all the way to Nano were eventually traced to a bug (less likely; and known bugs have been addressed AFAIK) or a configuration issue (**much** more likely).

The thornier issues I've witnessed had to do with permissions. For example, in one case, a buried and long forgotten deny rule prevented `dotnet.exe` from running. If you can run `dotnet.exe` from the command line when you login with your admin account but the identity of the IIS AppPool can't seem to fire it up and you see a permission denied error, then you'll find yourself troubleshooting a permissions issue.

**Comment by moozzyk** [comment] 2016-10-11 23:07
If you upgraded the packages using VS UI I know there was/is a bug where the VS NuGet UI will remove "tools" section from the project.json during the upgrade and move them to dependencies. As a result  the tools won't work. (https://github.com/NuGet/Home/issues/3008)

**Comment by valcs007** [comment] 2016-10-11 23:25
@GuardRex  - Sorry, i meant IIS 7.5. My prod server issue might be a permission issue? Any idea how to debug permission issue?

The current issue in my pre prod server with nww .Net core library seems to be not a permission issue.

@moozzyk - I am aware of the bug you mentioned but in my case, the project.json seems to be intact,

Anything else you need to reproduce the issue?

**Comment by GuardRex** [comment] 2016-10-11 23:32
> My prod server issue might be a permission issue?

Well, I was just using that as an example of a problem that can be more difficult to troubleshoot.

Did you run down the list of common errors at https://docs.asp.net/en/latest/publishing/iis.html#common-errors ... do any of the behaviors (browser, Application log, ANCM log) match?

**Comment by GuardRex** [comment] 2016-11-27 16:00
@valcs007 I'm currently reviewing issues for updates to the Publish to IIS doc. Did you ever determine the cause of (a) `publish-iis` tooling not running on publish, and (b) possible permission prob (0x80070005) when the app was trying to access some resource on startup?

**Comment by vaklove** [comment] 2016-11-28 21:03
I had a same issue . I changed  application pool identity  to network service account . Then I explicitly set the path to dotnet.exe in the web.config for the application to work properly as @danielyewright said in his comment . It works after set the path.

Thanks

**Comment by balarvs2002** [comment] 2016-12-10 02:58
Can asp.net Core app run on Windows server 2008 R2 with IIS 7 ?

After hosting on WS 2008 R2 with IIS7, Handler Mapping in IIS7 iteself throwin error ..
![untitled](https://cloud.githubusercontent.com/assets/17318223/21070764/998b1d3c-beb2-11e6-8bff-af1d1054a284.png)

Finally I feel, Asp.net core is not compatiable with WS 2008 R2 with IIS7

**Comment by GuardRex** [comment] 2016-12-10 03:00
@balarvs2002 Can you post your published `web.config` here so we can take a look?

**Comment by balarvs2002** [comment] 2016-12-10 03:17
posted my webconfig in my previous comments

**Comment by GuardRex** [comment] 2016-12-10 03:21
Seems ok. You installed the hosting bundle on the server and restarted?

https://aka.ms/dotnetcore_windowshosting_1_1_0

**Comment by GuardRex** [comment] 2016-12-10 03:22
If you only want to run the installer to install the ASP.NET Core Module, run the installer from an Administrator command prompt with ...

DotNetCore.1.1.0-WindowsHosting.exe OPT_INSTALL_LTS_REDIST=0 OPT_INSTALL_FTS_REDIST=0

**Comment by balarvs2002** [comment] 2016-12-10 03:26
I think.. I found the root cause.. aspcoremodule is not listed in IIS module section . This could be a reason. 

After installing  hosting bundle  I did not restart the server.

**Comment by GuardRex** [comment] 2016-12-10 03:27
ah ... yep ... that should do the trick then.

**Comment by GuardRex** [comment] 2016-12-10 03:28
you can also do a `net stop was /y` followed by a `net start w3svc`

**Comment by balarvs2002** [comment] 2016-12-10 03:30
Already done net stop was /y followed by a net start w3svc and still aspcore module is not listed in IIS7

**Comment by GuardRex** [comment] 2016-12-10 03:32
You can check the installer log for the hosting bundle in the temp folder. You may find that the installer is choking somewhere during the install.

If you do see it hitting an error, I suggest you open a new issue in the ANCM repo for them to take a look at it. https://github.com/aspnet/AspNetCoreModule/issues

**Comment by wgrs** [comment] 2016-12-30 15:00
I have the same issue ... 

Application 'MACHINE/WEBROOT/APPHOST/KEYSTONE' with physical root 'C:\Projects\GitRepositories\KeyStone\bin\Release\PublishOutput\' failed to start process with commandline '"C:\Program Files\dotnet\dotnet.exe" .\KeyStone.dll', ErrorCode = '0x80004005 : ff.

I have added the PATH but this error is still being thrown.

**Comment by GuardRex** [comment] 2016-12-30 16:59
@wgrs The exception matches https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#platform-conflicts-with-rid. Turn on stdout logging and see if you get more info.

**Comment by MinstrelPrince** [comment] 2016-12-30 17:18
I having a hard time hosting dotnet core app on win server 2008 R2 iis 7.5
the published self contain application runs fine from CLI using dotnet app.dll

Here are my file settings

web config
<?xml version="1.0" encoding="utf-8"?>
<configuration>

  <!--
    Configure your application settings in appsettings.json. Learn more at https://go.microsoft.com/fwlink/?LinkId=786380

  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="efueliteapi.exe" arguments=".\efueliteapi.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false"/>
  </system.webServer>
</configuration>

===========Project.json====================
{"runtimes": {
  "win10-x64":{},
  "win7-x64":{},
  "win8-x64":{},
  "win81-x64":{}
},
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1"
     // "type": "platform"
    },
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.CommandLine": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Dapper": "1.50.2",
    "Microsoft.AspNetCore.Cors":"1.1.0",
    "Microsoft.Extensions.Caching.Abstractions": "1.1.0",
    "Microsoft.Extensions.Caching.Memory": "1.1.0"
  },
  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final"
  },
  "frameworks": {
    "netcoreapp1.1": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ],
      "dependencies": {
        "System.Data.SqlClient": "4.1.0-*",
        "Microsoft.AspNetCore.Session": "1.0.0",
        "System.Text.Encodings.Web": "4.3.0",
        "System.Globalization": "4.3.0",
        "Microsoft.AspNetCore.Mvc": "1.1.0",
        "MailKit": "1.4.2.1",
        "Hangfire.Core": "1.6.8",
        "Hangfire.AspNetCore": "1.6.8",
        "Hangfire.SqlServer": "1.6.8",
        "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
        "Microsoft.AspNetCore.Razor.Tools": {
          "version": "1.0.0-preview2-final",
          "type": "build"
        }
      }
    }
  },
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },
  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },
  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },
  "scripts": {
    "postpublish": [
      "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
    ]
  },
  "tooling": {
    "defaultNamespace": "EfueliteAPI"
  }
}
================Program.cs=================
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.Configuration;

namespace EfueliteAPI
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var config = new ConfigurationBuilder()
                .AddCommandLine(args)
                .AddEnvironmentVariables(prefix: "ASPNETCORE_")
                .Build();

            var host = new WebHostBuilder()
                .UseConfiguration(config)
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
    }
}
======================Startup.cs============================
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Text;
using System.Xml;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using EfueliteAPI.Services;
using EfueliteAPI.Helpers;
using Hangfire;
using Hangfire.Storage;
using Hangfire.AspNetCore;
using Hangfire.SqlServer;
using Dapper;
using Microsoft.AspNetCore.Cors;
using Microsoft.Extensions.Options;
using Microsoft.Extensions.Caching.Memory;
namespace EfueliteAPI
{
    public class Startup
    {
        AppSettings _appSettings = new AppSettings();
        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            Microsoft.Extensions.DependencyInjection.OptionsConfigurationServiceCollectionExtensions.Configure<AppSettings>(services, Configuration.GetSection("EfueCon"));
            services.AddHangfire(x => x.UseSqlServerStorage(_appSettings.ConString));

           
            services.AddMemoryCache();
            services.AddMvc();



            services.AddTransient<IStudent, Student>();
            services.AddTransient<IAccountDept, AccountDept>();
            services.AddTransient<IAccountRenewal, AccountRenewal>();
            services.AddTransient<IAccountUpgrade, AccountUpgrade>();
            services.AddTransient<IAffiliateTutors, AffiliateTutors>();
            services.AddTransient<IAward, Award>();
            services.AddTransient<ICurrencyDeposit, CurrencyDeposit>();
            services.AddTransient<ICurrencyTransferNReceival, CurrencyTransferNReceival>();
            services.AddTransient<ICurrencyWithdrawal, CurrencyWithdrawal>();
            services.AddTransient<IDateTimeDifference, DateTimeDifference>();
            services.AddTransient<IEfueliteMail, EfueliteMail>();
            services.AddTransient<IFinances, Finances>();
            services.AddTransient<IForumService, ForumService>();
            services.AddTransient<IHitConversion, HitConversion>();
            services.AddTransient<IInformation, Information>();
            services.AddTransient<ILogistic, Logistic>();
            services.AddTransient<IQualityAssurances, QualityAssurances>();
            services.AddTransient<IQuestion, Question>();
            services.AddTransient<IQuestionXML, QuestionXML>();
            services.AddTransient<ISecurity, Security>();
            services.AddTransient<ISMSData, SMSData>();
            services.AddTransient<IUserSettings, UserSettings>();
            services.AddTransient<ISendEMail, SendEMail>();
            services.AddTransient<IRandomHelper, RandomHelper>();
            services.AddTransient<IListHelper, ListHelper>();
            services.AddTransient<ISecureGateWay, SecureGateway>();
            services.AddTransient<ITextMsgHelper, TextMsgHelper>();
            services.AddTransient<IQuestionComment, QuestionComment>();
            services.AddTransient<ICacheHelper, CacheHelper>();
            // services.AddDistributedMemoryCache(); // Adds a default in-memory implementation of IDistributedCache
            // services.AddSession();
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddScoped<HttpRequestHelper>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseCors("AllowSpecificOrigin");
            var options = new SqlServerStorageOptions
            {
                PrepareSchemaIfNecessary = false
            };
            Hangfire.GlobalConfiguration.Configuration.UseSqlServerStorage(_appSettings.ConString, options);
            app.UseHangfireDashboard("/dashboard");
            app.UseHangfireServer();
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            app.UseForwardedHeaders(new ForwardedHeadersOptions() { ForwardedHeaders = Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.All });
            app.UseMvc();
        }
    }
}

**Comment by GuardRex** [comment] 2016-12-30 17:21
@MinstrelPrince Generally, you need to enable stdout logging when the ANCM (ASP.NET Core Module) fails to start the process. The log usually helps sort out why the app is failing to start. If the process is starting but the app is failing, then try using app logging and the developer exception page to see if you can get more info. See the Publishing to IIS doc Troubleshooting Tips section at https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#troubleshooting-tips

**Comment by MinstrelPrince** [comment] 2016-12-30 17:29
@GuardRex , Thanks so much for this prompt response,

However I have enabled stdout logging in the current published release webconfig
Its a shared hosting and I dont have access to the server directly...

how do i get to view the log file????
IIS gives this error

HTTP Error 500.19 - Internal Server Error
The requested page cannot be accessed because the related configuration data for the page is invalid.
Detailed Error Information
Module	IIS Web Core
Notification	Unknown
Handler	Not yet determined
Error Code	0x80070005
Config Error	Cannot read configuration file due to insufficient permissions
Config File	\\?\E:\HostingSpaces......wwwroot\web.config

**Comment by GuardRex** [comment] 2016-12-30 17:35
@MinstrelPrince Ah ... shared hosting. We have a note on that here: https://docs.microsoft.com/en-us/aspnet/core/hosting/aspnet-core-module#aspnet-core-module-with-iis-shared-configuration

RE: The log file. It's created at the path you provide to `stdoutLogFile`. Just make sure that any folders you put in the path exist on the server, because the ANCM won't create folders if they don't exist ... it just doesn't write the log file if it can't find the folder to place it in. Devs usually put a `logs` folder in the deployed app and use a path of ... `stdoutLogFile=".\logs\stdout"` (a timestamp and `.log` file extension will be added for you).

**Comment by MinstrelPrince** [comment] 2016-12-30 17:48
@GuardRex 
Thanks sir,
There is a *logs* folder in same oath as the dotnet core app
I have this line in web config
stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout"

Still no log is written to the logs folder ....just having a screen

HTTP Error 500.19 - Internal Server Error
The requested page cannot be accessed because the related configuration data for the page is invalid.
Detailed Error Information
Module	IIS Web Core
Notification	Unknown
Handler	Not yet determined
Error Code	0x80070005
Config Error	Cannot read configuration file due to insufficient permissions
Config File	\?\E:\HostingSpaces......wwwroot\web.config

**Comment by GuardRex** [comment] 2016-12-30 17:56
@MinstrelPrince It's the shared hosting setup that's likely causing the problems for you. If you don't have access to the server, then you probably won't be able to fix this with the unsupported workaround ...

> The unsupported workaround is to disable the IIS Shared Configuration, run the installer, export the updated applicationHost.config file to the share, and re-enable the IIS Shared Configuration.

The MS devs are monitoring this discussion, so they may come in and say more when they get back after New Years. I think they're pretty much all out of the office for the holiday.

**Comment by MinstrelPrince** [comment] 2016-12-30 19:29
@GuardRex, thanks so much 
I'm much relieved 
I'll wait... 
Meanwhile I'll send the unsupported work around to the host... 
Please any work around or new release that solves this aches, you can notify me on princeefue@gmail.com

Thanks so much 
I appreciate you

**Comment by wgrs** [comment] 2017-01-02 11:42
After reviewing the stdout logs, my issue is that I cannot get the application pool identity to connect to the database. The app pool is No Managed Code and the application pool identity is set to my windows admin login on my machine. I tested the application pool identity and the message is a successful authentication. I created SQL Login and User but the application pool identity can NOT login.

**Comment by techjunkiejh** [comment] 2017-01-16 17:23
It's frustrating working with ASP.NET Core.  Things just stops working when a new version comes out.  As of 1/16/2017 this is what is working with version 1.1.0.  It's all about the project.json file you have to have the right combinations of settings to make it work.  Microsoft has to come up with a stable version soon.  It's a nice concept but it should also be stable too.  Maybe they should slow down and let developers take a breath.  

**So the basic thing to do to fix this issue is to define the tools and apps section separately.  These are the apps and tools settings.**  I will post the entire project.json file at the end of this post

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    }

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final"
  }

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [ "dotnet5.6", "portable-net45+win8" ]
    }
  }

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [ "wwwroot", "web.config" ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }

**Take out the imports that you have in the tools configuration as mentioned above.**

**Here is my entire project.json file that works**
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.Extensions.Caching.Memory": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Http.Extensions": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.AspNetCore.Session": "1.1.0"
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [ "dotnet5.6", "portable-net45+win8" ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [ "wwwroot", "web.config" ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

**Comment by cesarbs** [comment] 2017-01-17 20:24
Have you tried changing `Microsoft.NETCore.App` to `1.1.0`? Also, change your target framework `netcoreapp1.0` to `netcoreapp1.1`.

**Comment by ZEROxDEADC0DE** [comment] 2017-01-20 09:55
Hey everyone, i just faced a similar issue with the update from netcoreapp1.0 to 1.1

I updated the `"frameworks": {` section in the web-api projetcs `project.json` file to the following:  
```json
"frameworks": {
      "netcoreapp1.1": {
        "dependencies": {
          "Microsoft.NETCore.App": {
            "type": "platform",
            "version": "1.1.0"
          }
        },
        "imports": "dnxcore50"
      }
    },
```

The error logs weren't really that helpful. To get a more detailed version of the error you can run the project from the command line:
- Open cmd in the publish target directory
- Run `dotnet .\[YOUR_FILE].dll`

For me this resulted in an error message, indicating that i needed to install .net core framework version 1.1 on the server.  [Download link](https://www.microsoft.com/net/download/core#/current)

The `%LAUNCHER_PATH%` and `%LAUNCHER_ARGS%` placeholders in the `web.config` are currently not being replaced for me either. I'll let you know if i find a solution :)

**Comment by BlueGene89** [comment] 2017-03-06 07:27
The solution by @techjunkiejh works for me! The website can run and the log file is not empty any more! Thanks man!

**Comment by shiranGinige** [comment] 2017-03-11 02:30
I had this after converting from Core 1.0 to 1.1 and deleting and re-creating the web app fixed it.

**Comment by realvino** [comment] 2017-03-22 12:18
"Seems ok. You installed the hosting bundle on the server and restarted?
https://aka.ms/dotnetcore_windowshosting_1_1_0"

this solution work for me.. thanks.. @GuardRex

**Comment by GuardRex** [comment] 2017-03-22 20:03
@realvino np ... and this one: https://go.microsoft.com/fwlink/?linkid=837808 ... has a slightly later version of the ANCM IIRC. I believe it has a few patches in it (e.g., app_offline.htm casing issue for one).

**Comment by StingyJack** [comment] 2017-03-30 12:03
To see if this is a permissions related issue, you can try briefly changing the app pool to localsystem. If it works now, its a permission problem with either the program files folder or the web folder. Don't forget to change it back to app pool identity.

**Comment by muratg** [comment] 2017-05-12 21:49
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Closed by muratg** 2017-05-12 21:49 UTC

**Comment by zaagan** [comment] 2017-05-29 05:08
The reason for my issue was  that **Microsoft.AspNetCore.Server.Kestrel**  had somehow been removed though the project build successfully. I reinstalled it , and it worked.

**Comment by li2008kui** [comment] 2017-06-11 12:43
问题解决了！
原因是升级.NET Core版本后引起的问题。
查看你的xxx.runtimeconfig.json文件并修改version的值。
```{
  "runtimeOptions": {
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "1.1.2" <-- (1.1.0)此处改为安装版本即可
    },
    "configProperties": {
      "System.GC.Server": true
    }
  }
}

**Comment by mikebridge** [comment] 2017-07-08 07:12
@li2008kui's solution (via Google Translate) worked for me.  A working azure instance started giving me that error and only started working again until I changed `netcoreapp1.1` to `netcoreapp1.1.2` in my vs2017 `.csproj`:

```xml
<PropertyGroup>
    <TargetFramework>netcoreapp1.1.2</TargetFramework>
    ...
    <AssemblyName>Api</AssemblyName>
</PropertyGroup>
```
The underlying error for me was this:
```
Application 'MACHINE/WEBROOT/APPHOST/******' with physical root 'D:\home\site\wwwroot\' failed to start process with commandline 'dotnet .\Api.dll', ErrorCode = '0x80004005 : 8000808c.
```

**Comment by Structed** [comment] 2017-07-24 14:06
Thank you so much, @mikebridge! That was exactly what helped me. Running locally on console with ``dotnet run`` worked like a charm, but deploying to Azure App Services (IIS) would not work and result in that dreaded 502.

**Comment by bryoncline** [comment] 2017-10-11 01:56
I had the same issue and I did these steps:
1) converted the folder to an application
  I had c:\inetpub\wwwroot\publish
  publish was just a folder, right-click and converted to application
2) created a new application pool named "NoDotNet" and change the dot net to "no managed code".
3) changed the newly created application to use the new application pool

**Comment by agnimitra** [comment] 2018-02-13 08:29
I ran through the same issue today and have fixed by changing web.config file.
[https://stackoverflow.com/questions/38624453/asp-net-core-1-0-on-iis-error-502-5/48761913#48761913](https://stackoverflow.com/questions/38624453/asp-net-core-1-0-on-iis-error-502-5/48761913#48761913)

**Comment by bhandarip** [comment] 2018-08-09 16:10
I was setting up new server to run .net core. I got same issue. After restarting the server, issue is fixed.
So, make sure you start your server after installing .net core windows hosting.
Restarting the IIS didn't work for me.
