### ISSUE TITLE
Ensure Configuration Provider Used for Hosting Configuration

### ISSUE THREAD

**Issue by Michael-DST** [aspnet/Hosting#346] opened 2015-09-08 17:28 UTC
This is related to issue #269.  A great effort was made to make the Hosting Configuration File in a consistent/expected file format of .json, but the underlying issue was not fully addressed: As discussed in [another issue in Tooling](https://github.com/aspnet/Tooling/issues/140), users (and teams) enjoy and prefer their own data formats when describing objects used for configuration.  Ideally, the Hosting application will leverage the [configuration provider API](https://github.com/aspnet/Configuration) already available with ASP.NET to make it as consistent (and friendly) as the features already available.

Obviously, Json provider will be default, but others will providers can and should be used as well.  Yay for options. :smile:

**Comment by muratg** [comment] 2015-09-08 17:38
There are no current plans to do this. Closing.

**Closed by muratg** 2015-09-08 17:38 UTC

**Comment by Michael-DST** [comment] 2015-09-08 17:42
LOL @Tratcher why suggest to me to open up an issue around this if it was only going to be immediately closed?  And @muratg  ... there might not be current plans around this, but the point of opening issues to *create* plans around them. :)  Isn't it better to label this issue for a future version?

**Comment by davidfowl** [comment] 2015-09-08 18:06
I think the best way is for this to be in user code. Users can new up the hosting model using the API and provide any IConfiguration instance.

**Comment by Michael-DST** [comment] 2015-09-08 18:45
OK, we might actually be running into my confusion here.  I thought that the Hosting application was provided as a "web" command from ASP.NET projects to kick off hosting for their projects?  Are you suggesting that users go off and create their own Hosting command (by basically duplicating all of the functionality that is already in place with this Hosting command that we're talking about) instead of simply modifying the existing Hosting command with proper (and consistent) guidance that leverages an API that already exists -- and is built to fulfill exactly this scenario?  Does not compute.  But again, I might be confused.  It happens.  Enlighten me, please. :)

**Comment by Michael-DST** [comment] 2015-09-12 22:51
Well, I didn't get any additional answers to my question here, but I will say that it feels a little disorganized (and best) and maybe a little spiteful (at worst) to have one team member suggest opening an issue and then another to close it immediately without any meaningful discussion around it first.  I realize everyone is busy, but please do know that my intent here is to ensure great (cross-)use of your codebase and also the valuable guidance that this provides consumers of this code.

Additionally, I would also like to make the case that even though this feature is not in the current plans, this issue should remain open in case someone feels so inspired to create a PR around it, as well.  It could happen (that's what all this new-fangled opensourcery is all about, right?). :)  I also realize that keeping the backlog tidy is a value and a priority, and again I would point to at least making this a future feature for consideration instead of straight-up closing without any discussion around it.

As always, please feel free to correct me where I am wrong in my thinking here.  I am pretty much a newb around how all this works with all the sourcerers (new word, you're welcome) around here, but it is still a perspective and thought I would share how I see (and feel) it.

Thank you for any consideration (and feedback).

**Comment by davidfowl** [comment] 2015-09-12 23:07
> OK, we might actually be running into my confusion here. I thought that the Hosting application was provided as a "web" command from ASP.NET projects to kick off hosting for their projects? Are you suggesting that users create their own Hosting command (by basically duplicating all of the functionality that is already in place with this Hosting command that we're talking about) as opposed to modifying this command with the requested functionality? It would seem to me that this is an opportunity to highlight/showcase some great guidance that leverages an API in this impressive framework that already exists -- and is built to fulfill exactly this scenario. But hey, that's me. :)

We're not going to build a generic configuration system that can dynamically load configurations based on extensions because of the problems mentioned before. There isn't some uber configuration format reader than can dispatch to every possible format. The way the configuration API was intended to be used was having user code depend on the package that supported their format, create an `IConfiguration` instance and hand that into APIs.

Hosting in unique because it has a Program.Main that it calls into the user's `Startup` entry point so the application doesn't get a chance to configure the limited settings available in the hosting configuration file (which are quite minimal honestly). For these very narrow use cases, if json isn't a desirable format, it would be better for the application to redefine the web entry point by adding a Program.Main to their application and using the Hosting API similar to how the Program.Main in Hosting is using it. This gives the user more flexibility and allows the web command to still be used as an entry point from the command line.

It's 12 relevant lines of code:
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/Program.cs#L37-L49

> Well, I didn't get any additional answers to my question here, but I will say that it feels a little disorganized (and best) and maybe a little spiteful (at worst) to have one team member suggest opening an issue and then another to close it immediately without any meaningful discussion around it first. I realize everyone is busy, but please do know that my intent here is to ensure great (cross-)use of your codebase and also the valuable guidance that this provides consumers of this code.

There was no malice or spite in the issue closing, you were just a victim of bad timing. I will clarify though that we are not doing this feature for the reasons mentioned above.

If you have a specific scenario that you think we should reconsider then feel free to comment on this issue.

**Comment by Michael-DST** [comment] 2015-09-14 12:37
Great, thank you for taking time to address my points, David.  Much appreciated as always.

> It's 12 relevant lines of code:

Even duplicating 1 line of code is in violation of DRY. :)  Obviously, a priority should be placed on design that preserves code instead of duplicating it.  As you are well aware, it is possible to provide flexibility with smart design.  Again, this is also about guidance and best practices as well (i.e.., encapsulation over duplication). Asking developers to copy/paste, while easier to do, is also error-prone and ultimately affects quality (and said best practices).  Not to mention, it ultimately instills a counterproductive mindset towards solving problems.

> There was no malice or spite in the issue closing, you were just a victim of bad timing. I will clarify though that we are not doing this feature for the reasons mentioned above.
 
Well cool, thanks again for the explanation.  It does seem to me that this should be something that remains open for public interest/discussion and a possible PR by an ambitious contributor?  Or even better, the next release?

Along that note, I think it's safe to say that what I am after here has missed the boat for v1.0 (or 5, or whatever LOL).  I guess the best I can ask for going forward is awareness around this issue.  Obviously, with a developer on your team initially going with .ini and only to have it reversed to .json, it is clear that this desire for multiple data formats exists and is well-alive in every team (and developer).  My takeaway here is you have much more important issues to worry about over this one for your current release.  My consequent ask to you and your team is to please consider it and be aware of it for the next version and going forward.  Please and thank you!

**Comment by teyc** [comment] 2015-09-14 12:57
Hi @Michael-DST - Personally as an outsider, I wouldn't mind if the CoreCLR project stayed lean and mean and focus relentlessly on making it a viable platform on non-Windows platform. Currently, it's not quite there yet - and the risk of putting extra things on the list of open issues when major features are being culled for v1 (no SignalR, or WebPages), I think it'd be a misallocation of priorities. 
ps - I was checking out DragonSpark - looks like a cool project.
