### ISSUE TITLE
Could not load type 'System.Reflection.TypeInfo' from assembly

### ISSUE THREAD

**Issue by Cloud5-2016** [aspnet/Hosting#699] opened 2016-04-13 09:19 UTC
I have an application built in VS2015 with .NET4.5, I migrated it to VS2013 with .NET4.0. I downloaded the suitable package NewtonSoft.Json. when I run it locally it runs fine. But while running its exe on a remote server it throws below error:

```
Geotab.Serialization.JsonException: Exception of type 'Geotab.Serialization.JsonException' was thrown. ---> System.TypeLoadException: Could not load type 'System.Reflection.TypeInfo' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Geotab.Reflection.ReflectionHelper.GetTypeInfo(Type type)
```
Please advice

**Comment by davidfowl** [comment] 2016-04-13 09:22
I'm pretty confused as to what this has to do with anything. Can you be more specific and show the relevant parts of the project/code. Preferably upload a failing sample with instructions on how to reproduce the problem on github

**Comment by Cloud5-2016** [comment] 2016-04-13 10:34
Its a project for accessing Geotab website for retrieving vehicle status online. We use Geotab DLLs for this app. Its failing exactly at the stmt: List<Device> devices = api.Call<List<Device>>("Get", typeof(Device)); We use Newtonsoft.Json.8.0.3 package. It can be downloaded in VS PM console
Here is the code: 
```
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using System.Xml;
using System.Configuration;
using System.Linq;
using System.Data.SqlClient;
using System.Data;

using Geotab.Checkmate.ObjectModel;
using Geotab.Checkmate.ObjectModel.Engine;
using Geotab.Checkmate;


namespace Geotab_fleet
{
    /// <summary>
    /// Main program
    /// </summary>
    static class Program
    {

	static void Main(string[] args)
        {
            // Variables from command line arguments
            string server = "sts44.geotab.com";// args[0];
            string database = "recall_corporation";// args[1];
            string username = "sean.curran@recall.com";// args[2];
            string password = "Recall123";// args[3];
            DateTime d = DateTime.Now.Date.AddDays(-1);
            // d = d.Date;
            DateTime d1 = DateTime.Now.Date;
            string status = "Success";

            string fileName = "Mileage_" + d1.ToString("MM-dd-yyyy") + ".csv";// args[4];
            string fileName1 = d.ToString("yyyy-MM-dd") + "_Recall_Daily_Vehicle_List.csv";
            string fileName2 = d.ToString("yyyy-MM-dd") + "_Recall_Daily_Fleet_Summary.csv";
            string flgtxt = "RunStauts.txt";
            string logtxt = "Log.txt";

                        int filecount = 0;
            int errcount = 0;

            
            DateTime now = DateTime.Now;

            try
            {
                // Create Geotab API object.
                // It is important to create this object with the base "Federation" server (my.geotab.com) NOT the specific server (my3.geotab.com).
                // A database can be moved to another server without notice.
                API api = new API(username, password, null, database, server);

                // Get Devices
                Console.WriteLine("Time : " + DateTime.Now);
                Console.WriteLine("Getting Devices...");
                List<Device> devices = api.Call<List<Device>>("Get", typeof(Device));
                Console.WriteLine("Getting Odometer Readings...");
                using (StreamWriter writer = new StreamWriter(logtxt, true))
                {
                    writer.WriteLine(DateTime.Now + " : " + "Device count" + devices.Count());
                }

            }


            catch (Exception exception)
            {               
                using (StreamWriter writer = new StreamWriter(logtxt, true))
                {
                    writer.WriteLine(DateTime.Now + " : " + exception.ToString());
                }
                using (StreamWriter writer = new StreamWriter(flgtxt))
                {
                    writer.WriteLine(status);
                }
            }
            finally
            {
                using (StreamWriter writer = new StreamWriter(flgtxt))
                {
                    writer.WriteLine(status);
                }
                Console.ResetColor();
                Environment.Exit(0);
            }
        }
    }
}
```

**Comment by Cloud5-2016** [comment] 2016-04-13 11:24
We have an application connecting to Geotab website. It retrieves vehicle information online. We use Newtonsoft.Json.8.0.3 package. It shows error at the statement - List<Device> devices = api.Call<List<Device>>("Get", typeof(Device));. This code runs in VS locally. But when we place the executable files on a remote server, it gives error as mentioned earlier.
Here is the code:
```
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using System.Xml;
using System.Configuration;
using System.Linq;
using System.Data.SqlClient;
using System.Data;

using Geotab.Checkmate.ObjectModel;
using Geotab.Checkmate.ObjectModel.Engine;
using Geotab.Checkmate;


namespace Geotab_fleet
{
    /// <summary>
    /// Main program
    /// </summary>
    static class Program
    {

	static void Main(string[] args)
        {
            // Variables from command line arguments
            string server = "sts44.geotab.com";// args[0];
            string database = "Org_corporation";// args[1];
            string username = "email@email.com";// args[2];
            string password = "pswd";// args[3];
            DateTime d = DateTime.Now.Date.AddDays(-1);
            // d = d.Date;
            DateTime d1 = DateTime.Now.Date;
            string status = "Success";

            string fileName = "Mileage_" + d1.ToString("MM-dd-yyyy") + ".csv";// args[4];
            string fileName1 = d.ToString("yyyy-MM-dd") + "_Recall_Daily_Vehicle_List.csv";
            string fileName2 = d.ToString("yyyy-MM-dd") + "_Recall_Daily_Fleet_Summary.csv";
            string flgtxt = "RunStauts.txt";
            string logtxt = "Log.txt";

                        int filecount = 0;
            int errcount = 0;

            
            DateTime now = DateTime.Now;

            try
            {
                // Create Geotab API object.
                // It is important to create this object with the base "Federation" server (my.geotab.com) NOT the specific server (my3.geotab.com).
                // A database can be moved to another server without notice.
                API api = new API(username, password, null, database, server);

                // Get Devices
                Console.WriteLine("Time : " + DateTime.Now);
                Console.WriteLine("Getting Devices...");
                List<Device> devices = api.Call<List<Device>>("Get", typeof(Device));
                Console.WriteLine("Getting Odometer Readings...");
                using (StreamWriter writer = new StreamWriter(logtxt, true))
                {
                    writer.WriteLine(DateTime.Now + " : " + "Device count" + devices.Count());
                }

            }


            catch (Exception exception)
            {               
                using (StreamWriter writer = new StreamWriter(logtxt, true))
                {
                    writer.WriteLine(DateTime.Now + " : " + exception.ToString());
                }
                using (StreamWriter writer = new StreamWriter(flgtxt))
                {
                    writer.WriteLine(status);
                }
            }
            finally
            {
                using (StreamWriter writer = new StreamWriter(flgtxt))
                {
                    writer.WriteLine(status);
                }
                Console.ResetColor();
                Environment.Exit(0);
            }
        }
    }
}
```

**Comment by moozzyk** [comment] 2016-04-14 17:00
System.Reflection.TypeInfo is available since .NET Framework 4.5. If you still have a machine that has real .NET Framework 4 on it won't work.
Closing since this does not seem to be related in any way to AspNet Core.

**Closed by moozzyk** 2016-04-14 17:00 UTC
