### ISSUE TITLE
ASP.NET Core 1.0 app_offline.htm IIS 8.5 hosting with AspNetCoreModule

### ISSUE THREAD

**Issue by gencebay** [aspnet/Hosting#848] opened 2016-09-04 20:34 UTC
ASP.NET Core 1.0 App on hosting IIS 8.5 with AspNetCoreModule but during **msdeploy** that puts **app_offline.htm** (as I want) to the root path of application then each request getting only plain-text content of the **app_offline.htm** file. It doesn't seem to send Content-Type header to the browser. Its working on the IE but not the others! (webkit based)

**Comment by Tratcher** [comment] 2016-09-04 20:38
Duplicate of https://github.com/aspnet/IISIntegration/issues/178, which should have been fixed for 1.0

**Comment by muratg** [comment] 2016-09-07 21:24
@gencebay Are you using the latest AspNetCoreModule?

**Comment by gencebay** [comment] 2016-09-08 09:24
.NET Core and AspNetCoreModule versions:

![netcorestackdetails](https://cloud.githubusercontent.com/assets/879469/18344077/8d5c663e-75be-11e6-93f5-5906dab0c542.PNG)

**Comment by gencebay** [comment] 2016-09-08 10:00
When I uninstall .NET Core SDK Preview 2 and just remain .NET Core 1.0.0 Runtime then worked. Its getting right page for http://localhost:8080 but its getting **Http 503** for http://<hostname>:8080 when app_offline.htm in root path!

**Comment by Tratcher** [comment] 2016-09-08 13:28
http://localhost:8080 and http://hostname:8080 are different from IIS's perspective. What's your actual binding in IIS? Does http://hostname:8080 work without the app_offline.htm?

**Comment by gencebay** [comment] 2016-09-08 16:09
IIS binding is type:http port:8080 yes it is working without the app_offline.htm on http://hostname:8080

**Comment by Tratcher** [comment] 2016-09-08 18:46
I cannot repro this with IIS 10.

**Comment by gencebay** [comment] 2016-09-08 21:19
For your information, my release management steps are:

$(Build.DefinitionName) = Api
`dotnet publish -c Release -f net46 -o %cd%\bin\$(Build.DefinitionName)`

`msdeploy -verb:sync -source:contentPath=%cd%\bin\$(Build.DefinitionName)\ -dest:package=$(buildFullPath)\$(Build.DefinitionName).zip -declareParam:name="IIS WebApplication Name",defaultValue="$(Build.DefinitionName)"`

Package ready to deploy for production environment on UNC path then powershell executes on target machine with WinRM like:

--pseudo code: add the app_offline.htm to the $(Build.DefinitionName) IIS site root path

`msdeploy -verb:sync -source:package=\\servername\repo\releases\$(Build.DefinitionName)\$(Build.DefinitionName).zip -dest:contentPath=$(Build.DefinitionName) -enableRule:AppOffline`

--pseudo code: remove the app_offline.htm to bring back the application online

**Comment by Tratcher** [comment] 2016-09-12 17:14
This issue was moved to aspnet/IISIntegration#261

**Closed by Tratcher** 2016-09-12 17:14 UTC
