### ISSUE TITLE
Throwing in async void methods crash Kestrel

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Hosting#484] opened 2015-11-17 18:37 UTC
_From @NTaylorMullen on November 17, 2015 17:22_

A customer reported that throwing in their `TagHelper` caused Kestrel to crash. Turns out they were using `async void` which resulted in the crash. The original thread is [here](https://github.com/aspnet/Razor/issues/607).

Validated that Helios/IISExpress do not crash from the same bits. Helios must tie into the appdomain exceptions whereas IISExpress lets the underlying server crash and then reboots upon a new request. Here's the minimal repro `Startup.cs`:

```C#
public class Startup
{
    public void Configure(IApplicationBuilder app)
    {
        app.Run(async (context) =>
        {
            Throw();

            await context.Response.WriteAsync("Hello World!");
        });
    }

    public async void Throw()
    {
        throw new InvalidOperationException("You do bad");
    }

    public static void Main(string[] args) => WebApplication.Run<Startup>(args);
}
```

_Copied from original issue: aspnet/KestrelHttpServer#398_

**Comment by NTaylorMullen** [comment] 2015-11-17 18:37
_From @Tratcher on November 17, 2015 18:32_

I recommend moving this to Hosting, it's not a Kestrel specific issue.

**Comment by Tratcher** [comment] 2015-11-17 18:40
@NTaylorMullen claims this works for WebListener. Why?

**Comment by NTaylorMullen** [comment] 2015-11-17 18:52
Actually, scratch that about `WebListener`. Was crashing prior to the request being run (bug in ma code).

**Comment by benaadams** [comment] 2015-11-21 20:20
Either by design or a coreclr/corefx issue.

`async void` is a terrible thing to do :-1: 

Don't think you can even catch them with `TaskScheduler.UnobservedTaskException` listeners.

(from: http://www.jaylee.org/post/2012/07/08/c-sharp-async-tips-and-tricks-part-2-async-void.aspx)

> **async *void* methods and Exceptions**
> ...
> Second, when run, the whole process crashes.
>
> The reason behind this is the Synchronization Context used by the AsyncVoidMethodBuilder, being none in this example. When there is no ambient Synchronization Context, any exception that is unhandled by the body of an async void method is rethrown on the ThreadPool.
>
> While there is seemingly no other logical place where that kind of unhandled exception could be thrown, the unfortunate effect is that the process is being terminated, because unhandled exceptions on the ThreadPool effectively terminate the process since .NET 2.0. You may intercept all unhandled exception using the AppDomain.UnhandledException event, but there is no way to recover the process from this event.
>
> To make the matter a bit more difficult, this event is not available in Metro apps, because the AppDomain class has been removed.
>
> **What to Take Away**
>
> Here is what to remember about async Task/void methods:
> * async void methods are only suited for UI event handlers
> * async void methods outside the dispatcher raise unhandled exceptions on the thread pool, which terminate the process
> * ...

**Comment by muratg** [comment] 2015-12-08 18:45
This is a CoreFX issue.  Closing this.

**Closed by muratg** 2015-12-08 18:45 UTC

**Comment by shanselman** [comment] 2015-12-09 00:32
@muratg What's the issue #?

**Comment by benaadams** [comment] 2015-12-09 00:35
This is probably the most related https://github.com/dotnet/coreclr/issues/2144
