### ISSUE TITLE
[Announcment] The IHttpContextAccessor service is not registered by default

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#793] opened 2016-06-08 23:24 UTC
IHttpContextAccessor can be used to access the HttpContext for the current thread. However, maintaining this state has non-trivial performance costs so it has been removed from the default set of services. Developers that depend on it can add it back as needed:
`services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();`

RE: https://github.com/aspnet/HttpAbstractions/issues/473

**Comment by zigzag95** [comment] 2016-06-09 04:08
So of we don't inject httpcontext we won't have Access to User in our controllers ?

**Comment by Tratcher** [comment] 2016-06-09 04:45
@zigzag95 IHttpContextAccessor is only intended for accessing the HttpContext in locations where it's not directly available. HttpContext and User are directly available in MVC Controllers so you do not need IHttpContextAccessor.

**Comment by tugberkugurlu** [comment] 2016-06-09 06:46
In that sample, you are registering it as a singleton. Shouldn't it be a scoped instance?

**Comment by mikes-gh** [comment] 2016-06-09 08:01
`services.AddIdentity` registers this anyway.

https://github.com/aspnet/Identity/blob/79dbed5a924e96a22b23ae6c84731e0ac806c2b5/src/Microsoft.AspNetCore.Identity/IdentityServiceCollectionExtensions.cs#L54

A lot of applications will need identity so this change is moot really and to me is just confusing as if you use identity you get IHttpContextAccessor but if you don't it doesn't.
So if using identity you get IHttpContextAccessor 'magically'.
Even though HttpConext is available in controller I still want to avoid `new` on my objects and prefer DI.

Now it is not clear when you need to register IHttpContextAccessor.
What would be the result of registering it twice.

ie

```
services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();
            services.Configure<IdentityOptions>(options =>
            {
                options.Cookies.ApplicationCookie.LoginPath = new PathString("/default/Account/Login/");
            });

            services.AddMvc();
            services.AddAuthorization();
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
```

The above code runs fine buy is there a performance hit to AddIdentity reqistering IHttpContextAccessor and registering it myself.
I would prefer to register it explicitly as it is cleared to my code.

**Comment by davidfowl** [comment] 2016-06-09 08:14
> The above code runs fine but is there a performance hit to AddIdentity reqistering IHttpContextAccessor and registering it myself.

Performance hit? Is that speculation or did you measure?

> In that sample, you are registering it as a singleton. Shouldn't it be a scoped instance?

It's fine being a singleton because the backing store is async local.

**Comment by mikes-gh** [comment] 2016-06-09 08:26
@davidfowl 
> Performance hit? Is that speculation or did you measure?

I am just not sure of the mechanics of registering it again.

AddIdentity is already providing an instance of HttpContextAccessor but I prefer to explicitly register it.
I don't perceive any performance hit (I didn't notice when IHttpContextAccessor instatiation was removed from Hosting Either :-).

I just wanted to make sure there wasn't a problem registering it again.

**Comment by davidfowl** [comment] 2016-06-09 10:04
There is no problem registering it again and certainly no measurable performance hit.

**Comment by mikes-gh** [comment] 2016-06-09 10:27
@Eilon  re the advice to use
> `services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();`

Would it not be better to advise using the TryAdd version

`services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();`

since it may not be clear that the service may already be registered by another service and we don't need 2 instances.

That way if IHttpContextAccessor is already registered by another service eg `AddIdentity'  a duplicate is not created.  Other aspnet services use the TryAdd version for this reason I believe.
See my discussion above with @davidfowl

**Comment by brockallen** [comment] 2016-06-09 15:04
> >    In that sample, you are registering it as a singleton. Shouldn't it be a scoped instance?
> It's fine being a singleton because the backing store is async local.

Actually if you re-register it as a Transient on .NET Core then it doesn't work properly since the implementation for .NET Core is using a AsyncLocal which relies upon the instance variable to track the TLS storage slot.

**Comment by Tratcher** [comment] 2016-06-09 16:38
@mikes-gh Sure, TryAdd is slightly better, but shouldn't affect functionality or perf.

**Comment by mikes-gh** [comment] 2016-06-09 17:15
@Tratcher I may not be understanding the mechanics but if there is no performance impact to registering a second instance why was the default instance removed?

**Comment by Tratcher** [comment] 2016-06-09 17:39
Only one registered instance gets used so there is a perf difference between 0 and 1, but not between 1 and 2.

**Comment by mikes-gh** [comment] 2016-06-09 22:25
Ok got it thanks .  I still think the announcement should sugest TryAdd though.

**Comment by brockallen** [comment] 2016-06-09 22:42
> I still think the announcement should sugest TryAdd though.

It doesn't matter -- it must be a singleton, so doing additional DI config with different lifetimes won't work anyway.

**Comment by mikes-gh** [comment] 2016-06-10 06:33
@brockallen
TryAddSingleton is the same lifetime as AddSingleton.  The difference is TryAdd version checks for the existence of the  object in the  service collection and any only adds it  if it's not already there.  See Dependency Injection repo for the code.

**Comment by brockallen** [comment] 2016-06-11 15:09
> @brockallen TryAddSingleton is the same lifetime as AddSingleton. 

This distinction wasn't my point. My point was that the class (either by design or by accident) will only work as a singleton.

**Comment by ericwj** [comment] 2016-06-21 01:30
Conceptually the DI provider is a typed dictionary with the service type as the key. So any service can be registered in a for loop a thousand times, it won't have much effect apart from startup performance - which is negligible unless you actually do use a for loop.

I believe the scoping of any service is fixed once it is registered for the first time, I believe that's true for the implementation type as well - correct me if I'm wrong. I recall @DamianEdwards fixed a bug with caching on stage at a conference (//Build?) by simply registering a singleton before registering EF - which would register the same service type as transient. I'm just too lazy to test it right now, it'll probably take about two minutes...

**Comment by mikes-gh** [comment] 2016-06-21 07:43
Or maybe all service registering should be using  TryAdd logic.
Drop TryAdd and move the uniqueness check to Add method.
That would make sure the service collection correctly matches what will be instantiated.  That way the useless entries never make it into the collection..

**Comment by sandorfr** [comment] 2016-06-21 23:23
This announcement creates a very awkward feeling. The way it's stated gives the impression that we should not use it. But, identity is using it, so a vast majority of apps developed with aspnetcore will depend on it, so I guess (hope) that the cost of this is not that bad or they may be something extremely wrong with identity implementation.

**Comment by mikes-gh** [comment] 2016-06-22 08:33
> non-trivial performance costs 

@Tratcher The above is the justification for removal of IHttpContextAccessor by default.
Yet as @sandorfr  points out it will be in a LOT of web apps due to identity requiring it.

Should we be concerned about performance in all apps that use  identity?
This post does sound like it is discouraging use of IHttpContextAccessor but I'm not sure what to use as an alternative.

**Comment by Tratcher** [comment] 2016-06-22 15:59
@mikes-gh one of the major tenants of Asp.Net Core is pay-for-play, e.g. you only pay the costs of the components you use. Yes, many apps will use Identity and those apps will have higher costs than apps that don't (and not only because of IHttpContextAccessor). The added cost is not prohibitive, just it's unnecessary for other kinds of applications.

**Comment by sandorfr** [comment] 2016-06-22 18:11
> The added cost is not prohibitive

Thanks for clarifying that :).

**Comment by wangkanai** [comment] 2016-08-30 08:51
So how do you access the `HttpContext` from `IHttpContextAccessor` in configuring custom service now?
I'm trying to accessing `HttpContext` in [BrowserDetectorService](https://github.com/wangkanai/Browser/blob/dev/src/Wangkanai.Browser/BrowserDetectorService.cs) and get `null` when the app run.

**Comment by muratg** [comment] 2017-05-12 21:44
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Closed by muratg** 2017-05-12 21:44 UTC
Labels: Discussion

**Comment by AndreiRinea** [comment] 2017-11-09 11:20
The HttpContextAccessor seems to be registered by default in .NET Core 2.0.2. This is partially shown in [my issue on StackOverflow](https://stackoverflow.com/q/47190334/1796).

**Comment by Tratcher** [comment] 2017-11-09 19:41
No, the stack does not register it by default, but one of your dependencies may. For example ApplicationInsights registers it.

**Comment by turkelk** [comment] 2017-12-05 05:42
It is registered in debug mode but in publish mode it is not registered. What is the differences between them?

**Comment by ahmetsevgili** [comment] 2017-12-05 05:46
It is registered in debug mode but in publish mode it is not registered. What is the differences between them?

**Comment by promanchenko-softheme** [comment] 2017-12-06 20:01
@ahmetsevgili  I have the same problem. Have you already solved it? 

Help me, please

**Comment by Tratcher** [comment] 2017-12-06 20:09
That may be ApplicationInsights only registering it when enabled.

**Comment by DamianEdwards** [comment] 2017-12-06 20:13
Application Insights is automatically registered in your application when you launch it under the debugger in Visual Studio, such that you can see & search events coming from your application while debugging in the VS Application Insights search experience. This is the most likely cause of the `IHttpContextAccessor` being available in debug but not after the application is published. If you need it, please register is explicitly yourself in `ConfigureServices`.

**Comment by ahmetsevgili** [comment] 2017-12-07 07:44
@promanchenko-softheme, use like @Tratcher said that above. Both debug and publish mode work fine after adding 
`services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>(); `
line

my ConfigureServices snippet like below
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
```

**Comment by migajek** [comment] 2017-12-22 22:44
Visual Studio debugger registering `IHttpContextAccessor` is extremely misleading. It took me a while to find out what the real cause of my "bug" was

**Comment by chrispickford** [comment] 2018-04-12 10:47
Experienced this issue in a slightly different context to what's already been posted. When publishing an ASP.NET Core 2 API project via our CI process to an IIS server the following exception is raised:

> InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor'...

Locally, we're debugging using Kestral and the exception doesn't raise.

Adding `services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();` to the `RegisterServices(IServiceCollection)` method has resolved the issue in IIS, but I'm curious why this isn't an issue when self-hosting?

**Comment by davidfowl** [comment] 2018-04-12 10:49
That's going to be fixed in 2.1, it has to do with the fact that application insights was being injected in visual studio by default and adding those services but only when debugging. We're making some adjustments so we don't have a different debug/non-debug experience by default.

**Comment by mikes-gh** [comment] 2018-04-12 11:25
So does that mean adding back HttpContextAccessor service by default?

**Comment by davidfowl** [comment] 2018-04-12 11:31
> So does that mean adding back HttpContextAccessor service by default?

No

**Comment by ecabigting** [comment] 2018-04-12 11:42
hello @davidfowl was wondering if you can help me, i have the same issue 

`Application startup exception: System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'Web.Startup'.`

I have this line `services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();` in my Startup.cs
and my IIS host is running with `Microsoft.AspNetCore.Hosting version 2.0.1-rtm-125`

Suggestions? Thank you! :)

**Comment by mikes-gh** [comment] 2018-04-12 11:49
@davidfowl 

>No

How is it solved then?  Code analyzer to catch the dependency in debug build? or.....

**Comment by springy76** [comment] 2018-04-13 09:11
As `HttpContextAccessor` is just a wrapper around a single private **static** variable I see no reason why it should make any difference anywhere whether it is registered Singleton, Scoped or Transient.
