### ISSUE TITLE
Allow Startup.Configure to be async

### ISSUE THREAD

**Issue by yossarianeq** [aspnet/Hosting#536] opened 2015-12-22 17:15 UTC
When Startup.Configure method is async Task, I'd expect the system to await it's finish. 

It can be useful for, for example, configuring some database stuff inside the method. When I have Startup.Configure async void, application may start even before the Configure finished.

**Comment by Tratcher** [comment] 2015-12-22 17:30
Duplicate of:
https://github.com/aspnet/Hosting/issues/373
https://github.com/aspnet/Hosting/issues/29

**Closed by Tratcher** 2015-12-22 17:30 UTC
Labels: duplicate
