### ISSUE TITLE
ConsoleLifetime doesn't exit gracefully on sigterm

### ISSUE THREAD

**Issue by xqrzd** [aspnet/Hosting#1373] opened 2018-04-04 21:17 UTC
ConsoleLifetime uses `ApplicationLifetime.StopApplication()` to shut down, however StopApplication doesn't wait for the application to exit, it just signals a cancellation token. The application stops immediately, without a chance for any IHostedService instances to shut down.

WebHost has extension methods that wait inside the ProcessExit event for the host to stop. Could this be brought over to Microsoft.Extensions.Hosting?

I'm still not sure it's enough to allow the application's Main method to complete (if there was code after WaitForShutdownAsync), I feel like that might require changes in .NET Framework / Core, to allow the ProcessExit event to be canceled like Console.CancelKeyPress.

**Comment by Tratcher** [comment] 2018-04-05 12:24
We could make the events block until the lifetime is disposed. Disposing the di container is the last step of shutdown.

**Comment by Tratcher** [comment] 2018-04-11 22:02
@glennc @muratg we should look at this for RC1

**Comment by muratg** [comment] 2018-04-11 22:11
@Tratcher regression?

**Comment by Tratcher** [comment] 2018-04-11 22:12
Not exactly. The design didn't transfer cleanly to Generic Host.

**Comment by Tratcher** [comment] 2018-04-11 22:13
We'd want to make sure the fix didn't break the design before 2.1.

**Comment by Tratcher** [comment] 2018-04-12 16:57
Duplicate of https://github.com/aspnet/Hosting/issues/1329

**Closed by Tratcher** 2018-04-12 16:57 UTC
