### ISSUE TITLE
Allow hosting startup failures to be detected somehow

### ISSUE THREAD

**Issue by hiteshmadan** [aspnet/Hosting#1579] opened 2018-11-06 22:56 UTC

**Comment by Tratcher** [comment] 2018-11-06 23:04
Duplicate of https://github.com/aspnet/Hosting/issues/1151.

This has already been fixed for generic host (Start just throws). I doubt we'll make the breaking change required to web host, but for 3.0 we're rebuilding web host on top of generic host so it would inherit this change.

**Closed** 2018-11-06 23:04 UTC
