### ISSUE TITLE
Random KeyNotFoundException in ProxyTypeEmitter.GetProxyType during requests again TestServer

### ISSUE THREAD

**Issue by eduherminio** [aspnet/Hosting#1312] opened 2018-01-18 14:44 UTC
Not sure if this is the correct place to post this, but I'm experiencing the same issue described in https://github.com/aspnet/Mvc/issues/6292 & https://github.com/aspnet/EventNotification/issues/76, randomly getting the following error in requests against a `TestServer`  (Microsoft.AspNetCore.TestHost v2.0.1)

```
----- Inner Stack Trace -----
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Extensions.DiagnosticAdapter.Internal.ProxyTypeEmitter.GetProxyType(ProxyTypeCache cache, Type targetType, Type sourceType)
   at Microsoft.Extensions.DiagnosticAdapter.Internal.ProxyFactory.CreateProxy[TProxy](Object obj)
   at Proxy_Method_From_<>f__AnonymousType0`3_To_Void OnBeforeAction(Microsoft.AspNetCore.Http.HttpContext, IRouteData)(Object , Object , IProxyFactory )
   at Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.Write(String diagnosticName, Object parameters)
   at Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.System.IObserver<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.AspNetCore.Mvc.Internal.MvcCoreDiagnosticSourceExtensions.BeforeAction(DiagnosticSource diagnosticSource, ActionDescriptor actionDescriptor, HttpContext httpContext, RouteData routeData)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.TestHost.ClientHandler.<>c__DisplayClass3_0.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.TestHost.ClientHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
Result Message:	
System.AggregateException : One or more errors occurred. (The given key was not present in the dictionary.)
---- System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
```

Project configuration:
```xml
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
  </ItemGroup>
```

**Comment by Tratcher** [comment] 2018-01-18 18:22
That doesn't look like our usual multi-threading errors. This looks like a duplicate of https://github.com/aspnet/Mvc/issues/6292

**Comment by Tratcher** [comment] 2018-01-18 18:24
@jbagga

**Comment by jbagga** [comment] 2018-01-29 18:59
@eduherminio Is it possible for you to share a repro sample?

**Comment by eduherminio** [comment] 2018-01-29 19:07
I'll try to work something out within the next days, but I'm afraid it's not going to be an easy-to-reproduce behaviour (happened to me very rarely, <5% requests, in my dev environment).

**Comment by jbagga** [comment] 2018-01-30 19:46
@rynowak FYI 
Will it be overkill to change dictionary operations to TryAdd or AddOrUpdate? https://msdn.microsoft.com/en-us/library/ee378665(v=vs.110).aspx

**Comment by jbagga** [comment] 2018-01-31 00:02
@eduherminio Is this your test project? Could you share your application project? Specifically, which version of ASP.NET Core is your web application using?

**Comment by eduherminio** [comment] 2018-01-31 09:25
Here you are [a repro sample](https://github.com/eduherminio/aspnetHosting-Issue1312).
It's using .NET Core v2.0 & Microsoft.AspNetCore.TestHost v2.0.1.
To this date I've only detected my beloved `KeyNotFoundException` in  [`GetAndPost` test method](https://github.com/eduherminio/aspnetHosting-Issue1312/blob/master/KeyNotFoundException/API.TEST/SampleControllerTest.cs#L17).

**Comment by jbagga** [comment] 2018-02-06 20:26
I tried to repro with the sample but was unable to. I basically ran the Post request in the suspected test on a loop but no luck.

cc @rynowak to see if there is further action required.

**Comment by eduherminio** [comment] 2018-02-06 20:36
I'm getting the error running 50-60 tests (all of them making use of `HttpHelper` class) and allowing built-in Visual Studio parallel tests mode (which might or might not be relevant).
Despite of that, it only shows up ocasionally, that's why I stated the reproduction might not be easy :(

**Comment by rynowak** [comment] 2018-02-21 21:01
We managed to find a pretty reliable repro for this problem when multiple test servers are created. We are going to try and reduce this repro further to just involve the event notification code.

```
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.TestHost;
using System;
using System.Collections.Generic;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using Xunit;

namespace API.TEST
{
    class Program
    {
        public static string Uri { get; private set; } = "api/dtos/";

        public static void Main(string[] args)
        {
            Parallel.For<TestServer>(
    0,
    100,
    () =>
    {
        var hostBuilder = new WebHostBuilder().UseStartup<Startup>();
        return new TestServer(hostBuilder);
    },
    (i, state, server) =>
    {
        var client = server.CreateClient();
        DTO DTOToTest = new DTO(1, "str");

        DTO savedDTO = HttpHelper.Post(client, Uri, DTOToTest, out HttpStatusCode statusCode);
        Assert.Equal(HttpStatusCode.OK, statusCode);
        Validate(DTOToTest, savedDTO);

        DTO saveddtoFromServer = HttpHelper.Get<DTO>(client, Uri + savedDTO.Id, out statusCode);
        Assert.Equal(HttpStatusCode.OK, statusCode);
        return server;
    },
    (_) => { });
        }

        private static void Validate(DTO entityToCreate, DTO createdEntity)
        {
            Assert.NotNull(createdEntity);
            Assert.True(createdEntity.Id > 0);

            Assert.Equal(entityToCreate.Number, createdEntity.Number);
            Assert.Equal(entityToCreate.String, createdEntity.String);
        }
    }


}
```

**Comment by eduherminio** [comment] 2018-02-23 09:19
We've just detected some issues related to `Delete` calls too.
In this case, instead of exceptions, `InternalServerError` StatusCode have been detected as a result of some of our delete tests.

**Comment by jbagga** [comment] 2018-03-07 01:16
@eduherminio We tried to address a race condition we were able to repro for 2.1.0-preview2. You can try our nightly build on myget https://dotnet.myget.org/gallery/aspnetcore-dev to check if it works. You can always feel free to reopen the issue as well!

**Closed by jbagga** 2018-03-07 01:16 UTC
Labels: 3 - Done, investigate

**Comment by Plasma** [comment] 2018-07-10 23:47
Hey,

I'm on .NET Core 2.1.1, should this bug have been fixed? Just encountered it again.

Thank you

**Comment by eduherminio** [comment] 2018-07-10 23:55
I didn't have the chance to test new packages in the real project where this issue was detected, since it's still stuck on 2.0.x versions, but I thought it was solved too :/

**Comment by Tratcher** [comment] 2018-07-11 00:11
Same stack trace? If so please open a new issue in Home.

**Comment by Plasma** [comment] 2018-07-11 00:32
Figured it out, the latest ``Microsoft.ApplicationInsights.AspNetCore`` NuGet package 2.3.0 still references an older ``Microsoft.Extensions.DiagnosticAdapter`` with this bug (1.x). I've removed AppInsights.

**Comment by Tratcher** [comment] 2018-07-17 16:17
https://github.com/Microsoft/ApplicationInsights-aspnetcore
