### ISSUE TITLE
Publishing to IIS from VS

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/Hosting#672] opened 2016-03-23 21:54 UTC
Used to work.
I am using platform handler 1.2 on IIS 7.5
I am using rc2 vnext latest bits.
I am publishing via file share to iis using right click deploy.
This is the powershell script
When I publish I don't get any runtimes folder in approot.
Also my webconfig doesn't get copied as in my project
It is missing
```
      <environmentVariables>
        <environmentVariable name="HTTP_PLATFORM_APPL_PATH" value="/reports2" />
      </environmentVariables>
```

```
Publishing with publish method [FileSystem]
Publishing files to \\aesdatabase\reports2
Executing command ["C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -source:contentPath='C:\Users\mikes\AppData\Local\Temp\PublishTemp\Reports274\' -dest:contentPath='\\aesdatabase\reports2' -verb:sync -enableRule:DoNotDeleteRule -retryAttempts:2 -disablerule:BackupRule]
```
Maybe its because of dotnet cli transition ?

**Comment by Tratcher** [comment] 2016-03-23 21:59
Yes, VS doesn't know about RC2. Try `dotnet publish` from the command line.

**Comment by moozzyk** [comment] 2016-03-23 23:24
When using `dotnet publish`:
- make sure you [include `wwwroot` in your `content`](https://github.com/aspnet/cli-samples/blob/master/HelloMvc/project.json#L3)  otherwise it won't be published
- add [these](https://github.com/aspnet/cli-samples/blob/master/HelloMvc/project.json#L32-L37) to your project.json file - this will update your web.config accordingly (or create a new one if one does not exist)

**Comment by GuardRex** [comment] 2016-03-24 02:01
Hey @moozzyk ... curious b/c I have PowerShell doing my publishing and haven't checked out your `dotnet-publish-iis` tooling, does `dotnet-publish-iis` tooling publish `Release`, or would we still perform a `dotnet publish --configuration Release` with the tool to get `Release` output?

**Comment by moozzyk** [comment] 2016-03-24 02:36
@GuardRex - dotnet-publish-iis merely updates (or creates if needed) web.config file of a published application. It just takes the path to the folder the application was published to and goes to wwwroot opens web.config file and makes sure that httpPlatfomHandler (AspNetCoreModule) entries exists and sets the path to the executable.

**Comment by GuardRex** [comment] 2016-03-24 02:48
@moozzyk I see. I'm looking forward to checking it out. I was just wondering, because `dotnet publish` still provides `Debug` bits unless one calls for `Release` output explicitly. [It's still not clear yet if `Debug

**Comment by moozzyk** [comment] 2016-03-24 16:28
@GuardRex - My understanding is that Debug vs. Release is basically the setting that is eventually being passed to the compiler (csc?). When you do `dotnet publish` it will compile the project first and this is where the configuration setting is passed. Once the project is compiled the output is being published to the target folder. Finally, postpublish scripts are being run - which is how dotnet-publish-iis is hooked to the pipeline.

**Comment by mikes-gh** [comment] 2016-03-24 16:39
Still doesn't work for me. (And I tired hard)
Does my project json look OK?
```
{
    "version": "1.0.0-*",

    "commands": {
        "web": "Reports2"
    },
    "compilationOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true
    },
    "dependencies": {
        "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-*",
        "Microsoft.AspNetCore.Authentication.Facebook": "1.0.0-*",
        "Microsoft.AspNetCore.Authentication.Google": "1.0.0-*",
        "Microsoft.AspNetCore.Diagnostics": "1.0.0-*",
        "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-*",
        "Microsoft.AspNetCore.Hosting": "1.0.0-*",
        "Microsoft.AspNetCore.HttpOverrides": "1.0.0-*",
        "Microsoft.AspNetCore.Identity": "1.0.0-*",
        "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-*",
        "Microsoft.AspNetCore.IISPlatformHandler": "1.0.0-*",
        "Microsoft.AspNetCore.Mvc": "1.0.0-*",
        "Microsoft.AspNetCore.Mvc.Dnx": "1.0.0-*",
        "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-*",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
        "Microsoft.AspNetCore.StaticFiles": "1.0.0-*",
        "Microsoft.EntityFrameworkCore.Commands": "1.0.0-*",
        "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-*",
        "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.0-*",
        "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-*",
        "Microsoft.Extensions.Configuration.Json": "1.0.0-*",
        "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-*",
        "Microsoft.Extensions.Logging": "1.0.0-*",
        "Microsoft.Extensions.Logging.Console": "1.0.0-*",
        "Microsoft.Extensions.Logging.Debug": "1.0.0-*",
        "MailKit": "1.3.0-beta7"
    },
    "tools": {
        "dotnet-publish-iis": "1.0.0-*",
        "dotnet-razor-tooling": "1.0.0-*",
        "dotnet-ef": "1.0.0-*"
    },
    "exclude": [
        "wwwroot",
        "node_modules"
    ],
    "frameworks": {
        "netstandardapp1.5": {
            "dependencies": {
                "NETStandard.Library": "1.0.0-*"
            },
            "imports": [
                "dnxcore50",
                "portable-net45+win8"
            ]
        },
        "net451": {
            "dependencies": {
                "hiqpdf": "9.0.0"
            },
            "frameworkAssemblies": {
                "System.ComponentModel": ""
            }


            }
        },
        "publishExclude": [
            "**.user",
            "**.vspscc"
        ],
        "scripts": {
            "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ]
        }

    }
```
Running the command
```C:\Users\mikes\Projects\Reports2\Main\Reports2\src\Reports2>dotnet publish-iis
Could not resolve coreclr path

C:\Users\mikes\Projects\Reports2\Main\Reports2\src\Reports2>
```

**Comment by moozzyk** [comment] 2016-03-24 16:44
@mikes-gh - I assume restore worked fine. if you try `dotnet run` does it work? What feeds are you using and what is your dotnet version (dotnet --version)? If I have this information I could try reproducing it.

**Comment by mikes-gh** [comment] 2016-03-24 20:59
```
C:\Users\mikes\Projects\Reports2\Main\Reports2\src\Reports2>dotnet --version
.NET Command Line Tools (1.0.0-beta-001935)

Product Information:
 Version:     1.0.0-beta-001935
 Commit Sha:  0e92937850

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 Runtime Id:  win7-x64

C:\Users\mikes\Projects\Reports2\Main\Reports2\src\Reports2>
```
dotnet restore ok.
dotnet build ok

```
C:\Users\mikes\Projects\Reports2\Main\Reports2\src\Reports2>dotnet ef
Could not resolve coreclr path

C:\Users\mikes\Projects\Reports2\Main\Reports2\src\Reports2>
```

**Comment by mikes-gh** [comment] 2016-03-24 21:09
Oh maybe coreclr x86 with dotnet x64 mismatch or arch

Whats the consensus on architectures btw.  Should I be sticking to x86 all round?

**Comment by moozzyk** [comment] 2016-03-24 21:18
if you are using dotnet you are not using dnx and therefore what dnvm list shows is irrelevant.

**Comment by mikes-gh** [comment] 2016-03-25 09:56
Didnt realise that.,
So how does an app run get published with dotnet.  
Were are the core libraries stored/compiled to.   The dotnet magic seems confusing to me.

The reason I ask is because this may be a path thing.  When installing dotnet cli via administrator prompt, path variables are not appended to the current user but to adminnistator.

**Comment by moozzyk** [comment] 2016-03-25 21:06
@mikes-gh - I looked a bit into this today. The `Could not resolve coreclr path` error is because you have a newer version of dotnet and the `publish-iis` tool was not updated accordingly to work with this version. There is even more changes in dotnet in this area and we are trying to bring aspnet tools up to date as we speak.

With dotnet you bring the runtime as the package. So, you select your runtime version just by setting it as a dependency in your project.json (dotnet is just a set of tools which are separate from the runtime). The dotnet build/run workflow is actually less magic then it was in dnx - in dnx the application was built at runtime. In dotnet things are more traditional - the application is built (can be done implicitly before you `dotnet run` or `dotnet publish`) before it can be run and you have outputs on disk. 

If you can run your application with `dotnet run` then running any tool should also work - all in all dotnet was capable of resolving the runtime for the app so it should be able to resolve the runtime for tools as well - as I said we are looking into fixing this.

**Comment by muratg** [comment] 2016-04-05 21:40
We'll need to see if this is still an issue in 1.0.0 with the newer VS tooling.

**Comment by LeandroPT** [comment] 2016-04-12 14:54
not working
**\cli-samples-master\HelloMvc>dotnet --info**
.NET Command Line Tools (1.0.0-rc2-002347)

Product Information:
 Version:     1.0.0-rc2-002347
 Commit Sha:  5f2183489f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**dnvm list**
```
Active Version           Runtime Architecture OperatingSystem Alias
------ -------           ------- ------------ --------------- -----
       1.0.0-rc1-final   clr     x64          win
       1.0.0-rc1-final   clr     x86          win
       1.0.0-rc1-final   coreclr x64          win
       1.0.0-rc1-final   coreclr x86          win
       1.0.0-rc1-update1 clr     x64          win
       1.0.0-rc1-update1 clr     x86          win
       1.0.0-rc1-update1 coreclr x64          win
       1.0.0-rc1-update1 coreclr x86          win
       1.0.0-rc1-update2 clr     x86          win
       1.0.0-rc1-update2 coreclr x64          win
       1.0.0-rc2-16357   clr     x86          win
       1.0.0-rc2-20221   clr     x86          win
       1.0.0-rc2-20221   coreclr x64          win
       1.0.0-rc2-20222   clr     x86          win
  *    1.0.0-rc2-20222   coreclr x64          win             default

```
**cli-samples-master\HelloMvc>dotnet publish -o bin\pub**
```
Publishing HelloMvc for .NETCoreApp,Version=v1.0
Project HelloMvc (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.CommandLineUtils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.AspNetCore.Tools.PublishIIS.Program.Main(String[] args)
Published to bin\pub
Published 1/1 projects successfully
```

**Comment by GuardRex** [comment] 2016-04-12 15:31
@LeandroPT 

Side Note: DNX (the runtimes you listed with the `dnvm` command) are not in use for `dotnet cli`. DNX is going away and doesn't have a bearing on your issue.

The `dotnet-publish-iis` tool looks to be involved in this exception. AFAIK the tool is under development (e.g., https://github.com/aspnet/IISIntegration/issues/109).

If you would like to temporarily try publishing the app without the tool, you can follow the steps below.

In `project.json`, remove ...
```json
"tools": {
  "dotnet-publish-iis": "1.0.0-*"
},
"scripts": {
  "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath%"
}
```
Confirm your `web.config` paths are set correctly ...
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <aspNetCore forwardWindowsAuthToken="true" processPath="dotnet" arguments=".\HelloMvc.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" startupTimeLimit="3600" />
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
  </system.webServer>
</configuration>
```
You'll need to add a `logs` folder to the project and put a fake text file into it to get the folder to publish (there is an open issue on that bug). Add the `logs` folder to the `content` section of `project.json`. Add the `web.config` file there, too, since the `dotnet-publish-iis` tool will not be used with the app ...
```json
"content": [
    "wwwroot",
    "Views",
    "logs",
    "web.config"
],
```

**Comment by mikes-gh** [comment] 2016-04-12 16:02
I can get dotnet publish to work OK now.

dotnet ef and dotnet razor-tooling both run

However if I try and use dotnet publish-iis
from the command line or in a postpublish script I get

I get
```
No executable found matching command "dotnet-publish-iis"
```
I am only building for net461 (no core targets)

Is this because dotnet publish-iis is not cross compiling like the other tools.

**Comment by muratg** [comment] 2016-04-12 16:08
@mikes-gh You may be hitting https://github.com/dotnet/cli/issues/2071

**Comment by moozzyk** [comment] 2016-04-12 16:28
publish-iis is in a Heisenber state right now. The old publish-iis (in the dotnet-publish-iis package) spits out the config for httpPlatformHandler and not for aspNetCoreModule. On top of that I don't think it accounted for the change where the web.config file was moved out of the wwwroot. The new publish-iis tool (from the Microsoft.AspNetCore.Server.IISIntegration.Tools) cannot work yet since the changes I made to cli to make the scenario where the package name is different from the dll inside the package) have not propagated to our build yet. At the moment I would recommend creating the web.config manually while I am working on sorting things out.

**Comment by mikes-gh** [comment] 2016-04-12 16:36
Ok got it.  Bit confusing having a new package different to tool name. Whats the resoning behind that.  It might confuse new users.

So to clarify  dotnet-publish-iis package is being replaced by Microsoft.AspNetCore.Server.IISIntegration.Tools.

Will that go in the tools section aswell.?

**Comment by moozzyk** [comment] 2016-04-12 16:43
It will look something like this in project.json:

```
 "tools": {
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-*"
    },
    "scripts": {
      "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath%"
    }
```

There are pros and cons of each approach. We discussed it a lot and we settled on new names for each our tools (not only publish-iis). The work is being tracked here: https://github.com/aspnet/Coherence-Signed/issues/243

**Comment by GuardRex** [comment] 2016-04-12 16:44
@moozzyk That link 404's.

**Comment by mikes-gh** [comment] 2016-04-12 16:49
Looks like a private repo

**Comment by moozzyk** [comment] 2016-04-12 16:51
Yeah, forgot about this...

**Comment by mikes-gh** [comment] 2016-04-12 16:57
So to clarify
We'll have 

Microsoft.EntityFrameworkCore.Tools
Microsoft.AspNetCore.Mvc.Tools

aswell?

**Comment by moozzyk** [comment] 2016-04-12 17:03
Yes, something along these lines.

**Comment by LeandroPT** [comment] 2016-04-12 17:45
@GuardRex

**Comment by muratg** [comment] 2016-05-19 18:58
Closing this one, if you are still hitting this issue, please file another bug.

**Closed by muratg** 2016-05-19 18:58 UTC
