### ISSUE TITLE
Could not load file or assembly 'Microsoft.AspNetCore.AzureAppServices.HostingStartup'

### ISSUE THREAD

**Issue by kspearrin** [aspnet/Hosting#1246] opened 2017-10-27 12:16 UTC
I am not sure if this is the correct repo for this or not, but I could not find where `Microsoft.AspNetCore.AzureAppServices.HostingStartup` is coming from. Please redirect me if necessary.

We recently updated to ASP.NET Core 2.0 (MVC apps) on our production instances running in Azure App Service. I have noticed some seemingly random instability and "crashes" happening on the app services since, which eventually self-correct themselves. Calls to the app services time out during these episodes. System logs show this when the crashes occur:

```
 {
    "EventIdHash": 933752513,
    "Timestamp": "2017-10-27 12:03:43.686+00:00",
    "Level": "Fatal",
    "Message": "Hosting startup assembly exception",
    "MessageTemplate": "Hosting startup assembly exception",
    "Exception": {
      "Message": "Startup assembly Microsoft.AspNetCore.AzureAppServices.HostingStartup failed to execute. See the inner exception for more details.",
      "Data": {},
      "InnerException": {
        "ClassName": "System.IO.FileNotFoundException",
        "Message": "Could not load file or assembly 'Microsoft.AspNetCore.AzureAppServices.HostingStartup' or one of its dependencies. The system cannot find the file specified.",
        "Data": null,
        "InnerException": null,
        "HelpURL": null,
        "StackTraceString": "   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)\r\n   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)\r\n   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)\r\n   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)\r\n   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)",
        "RemoteStackTraceString": null,
        "RemoteStackIndex": 0,
        "ExceptionMethod": "8\n_nLoad\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Reflection.RuntimeAssembly\nSystem.Reflection.RuntimeAssembly _nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)",
        "HResult": -2147024894,
        "Source": "mscorlib",
        "WatsonBuckets": null,
        "FileNotFound_FileName": "Microsoft.AspNetCore.AzureAppServices.HostingStartup",
        "FileNotFound_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog].\r\n"
      },
      "StackTrace": null,
      "HelpLink": null,
      "Source": null,
      "HResult": -2146233079
    },
    "Properties": {
      "EventId": {
        "Id": 11
      },
      "SourceContext": "Microsoft.AspNetCore.Hosting.Internal.WebHost"
    }
  },
```

After things self-correct themselves, everything seems stable and working well.

**Comment by Tratcher** [comment] 2017-10-27 12:23
It's this a .Net 4.x app or .Net Core 2.0? (Asp.Net Core supports both). The error looks like 4.x.

**Comment by kspearrin** [comment] 2017-10-27 12:25
We target both frameworks, but when we deploy to App Services, it is targeting net461. See https://github.com/bitwarden/core/tree/master/src/Api for source.

**Comment by kspearrin** [comment] 2017-10-27 12:34
Here is an example of an event occurring on our app service plan. It lasts a few minutes then things go back to normal (I'm guessing after the instance restarts).

![image](https://user-images.githubusercontent.com/1190944/32104161-62a3b9c8-baf1-11e7-8ff4-a095ff10a722.png)

![image](https://user-images.githubusercontent.com/1190944/32104253-a1f3ce1a-baf1-11e7-9f48-d79022c84d21.png)

**Comment by Tratcher** [comment] 2017-10-27 12:55
@muratg please assign someone to repro this, HostingStartup isn't well tested for .NET 4.x.

There are several levels to this:
A) .NET 4.x apps can't use the .All metapackage so they don't get a reference to this HostingStartup package by default. Adding a reference would prevent the exception.
B) The SiteExtension activates this HostingStartup indiscriminately for both .NET 4.x and .NET Core 2 apps. Removing the site extension from your app would help, but VS adds it again when you publish.
C) Hosting is supposed to catch all HostingStartup exceptions and log them, it shouldn't crash the app. How is this one getting through?
D) Why is the crash intermittent? The exception should always be happening due to A and B, and whatever's wrong with C should at least be consistently wrong.

**Comment by kspearrin** [comment] 2017-10-27 13:01
@Tratcher Are you suggesting that we can add a direct nuget reference for `Microsoft.AspNetCore.AzureAppServices.HostingStartup` as a workaround? I'd like to stabilize this production app if possible.

**Comment by Tratcher** [comment] 2017-10-27 13:02
Yes, that should work. You could also uninstall the Asp.Net Core site extension in the app services portal.

**Comment by Tratcher** [comment] 2017-10-27 13:10
Code links for the HostingStartup loading:
https://github.com/aspnet/Hosting/blob/e127224812d6fa30469f5c30f3f6bea43fb27b26/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L200-L214
https://github.com/aspnet/Hosting/blob/rel/2.0.0/src/Microsoft.AspNetCore.Hosting/Internal/WebHost.cs#L144-L150
https://github.com/aspnet/Hosting/blob/e4350945c56d69523fe36bf33c58b955db3d8985/src/Microsoft.AspNetCore.Hosting/Internal/HostingLoggerExtensions.cs#L29-L52

This suggests the exception handling and logging are working correctly. Is it possible that your app always shows logs error on startup and it's crashing for an unrelated reason?

**Comment by kspearrin** [comment] 2017-10-27 13:18
If that is the case I suppose a possible scenario is that something else is crashing the apps and this is just a log that happens whenever the apps come back online. It is hard to tell the difference since they both would be happening at approx the same time.

We'll continue to investigate. I have added the suggested nuget reference to the prod deployments for now.

**Comment by kspearrin** [comment] 2017-10-27 14:28
@Tratcher Wouldn't I see these logs every time I restart the application though?

**Comment by Tratcher** [comment] 2017-10-27 14:33
Yes, I would expect that. Unless the intermittent issue is with B, the activation.

**Comment by muratg** [comment] 2017-10-27 16:02
@davidfowl Any thoughts on this?

**Comment by davidfowl** [comment] 2017-10-28 04:29
> System logs show this when the crashes occur:

What are these "system logs"?

**Comment by kspearrin** [comment] 2017-10-28 04:31
It’s just serilog sinked to document db.

**Comment by davidfowl** [comment] 2017-10-28 04:36
How did you verify that there was an application crash?

**Comment by kspearrin** [comment] 2017-10-28 04:39
I didn’t actually. I just assumed there was since all api endpoints were timing out when trying to access them. Even the most basic “alive” api which just returns DateTime.Now and nothing more. Compared that with the graphs and the logs and just assumed the thing crashed. Maybe it didn’t?

**Comment by davidfowl** [comment] 2017-10-28 04:46
If it did I don't think it's related to the `HostingStartup`.

**Comment by kspearrin** [comment] 2017-10-28 04:51
I will say that since I updated the deployments with the previous suggestion to include the app sevices nuget ref explicitly in the net461 project I have not seen this happen again in the past 16 hours, whereas it happened twice in the 8 hours prior to that change. Still testing...

**Comment by kspearrin** [comment] 2017-10-29 00:01
So I am now confident there was something else that was causing the "crashing" and instability here that I've now resolved. The `AzureAppServices.HostingStartup` errors were just a red herring.

I suppose this can be closed, unless you are still interested in investigating this exception which I have not seen since adding the nuget package reference directly to my net461 project.

**Comment by davidfowl** [comment] 2017-10-30 04:30
Is there another exception?

**Comment by muratg** [comment] 2017-11-07 23:15
@glennc Could you ping tooling folks to look into this? Site extensions being applied to only .NET Core may be a temporary solution.  Alternatively, if we move all the dependencies of the site extensions to the site extensions packages (we can possibly do this in 3.0.0 where we remove these from the .ALL metapackage) this may just work on .NET Framework too.

**Comment by kspearrin** [comment] 2017-11-09 03:17
So I was trying to get application insights working with the same azure web app today and app insights would never pick it up for some reason. So finally I looked at the server logs again and I see this happening:

```
 {
    "Level": "Fatal",
    "Message": "Hosting startup assembly exception",
    "MessageTemplate": "Hosting startup assembly exception",
    "Exception": {
      "Message": "Startup assembly Microsoft.AspNetCore.ApplicationInsights.HostingStartup failed to execute. See the inner exception for more details.",
      "Data": {},
      "InnerException": {
        "ClassName": "System.IO.FileNotFoundException",
        "Message": "Could not load file or assembly 'Microsoft.AspNetCore.ApplicationInsights.HostingStartup' or one of its dependencies. The system cannot find the file specified.",
        "Data": null,
        "InnerException": null,
        "HelpURL": null,
        "StackTraceString": "   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)\r\n   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)\r\n   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)\r\n   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)\r\n   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)",
        "RemoteStackTraceString": null,
        "RemoteStackIndex": 0,
        "ExceptionMethod": "8\n_nLoad\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Reflection.RuntimeAssembly\nSystem.Reflection.RuntimeAssembly _nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)",
        "HResult": -2147024894,
        "Source": "mscorlib",
        "WatsonBuckets": null,
        "FileNotFound_FileName": "Microsoft.AspNetCore.ApplicationInsights.HostingStartup",
        "FileNotFound_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog].\r\n"
      },
    },
    "Properties": {
      "EventId": {
        "Id": 11
      },
      "SourceContext": "Microsoft.AspNetCore.Hosting.Internal.WebHost"
    }
  },
```

Following the same suggestion @Tratcher mentioned previously, I manually added `Microsoft.AspNetCore.ApplicationInsights.HostingStartup` to the project, deployed again and finally app insights started working.

**Comment by clement911** [comment] 2017-11-18 04:25
I'm hitting the same exception our production Azure environment, after upgrading to asp.net core 2.0 
and run with .net 4.6.1
It doesn't happen when running on my dev machine with VS.

It doesn't seem fatal, but of course, this is worrying to see exceptions in prod.

1) Should I be worried about this?
2) Should I add a ref to the nuget package Microsoft.AspNetCore.AzureAppServices.HostingStartup?
3) Why is this happening?

Note: The app doesn't use Application Insights. Or At least not intentionally, these magical 'lighting up' things are really scare me. Please no magic!

**Comment by Tratcher** [comment] 2017-11-18 05:46
1. No, it's harmless, just noisy.
2. Only if you want to get rid of the noise, or use AI.
3. We have this feature working well for Core but it's not fully developed for net461, it doesn't know where to find the dll yet.

**Comment by clement911** [comment] 2017-11-18 06:20
Thanks, I appreciate the quick reply!

**Comment by isaac2004** [comment] 2018-04-19 19:40
@Tratcher to piggy back on this, I see this in AI occasionally for Core 2.0. I will add the nuget package directly and comment if that does not resolve this.

**Comment by dcadlereii** [comment] 2018-04-28 18:47
I believe I am getting a similar error as the OP has listed. 

My log stream in Azure for the web app is throwing "System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.AzureKeyVault.HostingStartup, Culture=neutral, PublicKeyToken=null'."

This only happens if I use the Kudu ZipDeploy REST endpoint for deployment. It does not occur if I use VS2017 publish for deployment.  I have documented this issue in StackOverflow [here](https://stackoverflow.com/questions/50063851/publishing-to-azure-via-kudu-zipdeploy-using-powershell-causes-a-401-when-i-try?noredirect=1#comment87161432_50063851).

My API project uses ASP.NET Core 2.0 and netcoreapp2.0 but I have two additional class library projects that my API uses that multi-targeting as follows;

  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.0;netstandard2.0</TargetFrameworks>
  </PropertyGroup>

I don't know if this is related to the issues already discussed in this thread since they were talking about Framework 4.6.1 but the error message seem to be the same.

In my case, the result is that I get a 401 unauthorized message after using ZipDeploy for deployment of the package and when this happens, I see the FileNotFoundException implicating the Microsoft.AspNetCore.AzureKeyVault.HostingStartup file.

The point I am making here is that a file is missing that is related to Azure HostingStartup when I deploy a project that is not purely .Net Core 2.0. I will try to explicitly add that lib to my multi-targeted class libraries to see if it makes a difference.

**Comment by fiksen99** [comment] 2018-08-14 00:44
We are seeing the same error in our ASP.NET Core 2.0 app with net462 on Azure Web App services. These errors appear after a deployment, though infrequently. When we do see this error, the site is now down until (I believe) a redeployment. Even a restart doesn't bring it up.

The above thread indicates a few conflicting thoughts as to whether including the Hosting nuget package explicitly, or turning off the ASP.NET Core extension will fix this issue. Is there a recommended fix for our apps?

Note, I have tried deleting the extension from our app in staging environment and we still see the HTTP Error 502.5 - Process Failure message when hitting the site.

**Comment by fiksen99** [comment] 2018-08-14 00:57
I have confirmed that redeploying the same bits to our Azure Web App resulted in this issue too.

**Comment by Tratcher** [comment] 2018-08-14 03:16
@fiksen99 this is a known issue on net462, but it should not bring down your application, it should be logged and ignored. Do you see any other errors in your app logs?

**Comment by fiksen99** [comment] 2018-08-23 02:31
@Tratcher, I belive you are correct, I believe whenever our service was crashing at startup, we saw this logged an attributed it toward the crash, however we now see a healthy service, and still see the logs. So likelihood is that this isn't the critical issue we were thinking it was.

We have monitoring over our LogCritical logs, we can work around this, but can we expect a fix for this issue?

**Comment by Tratcher** [comment] 2018-08-27 19:56
We don't anticipate making any product changes soon but there are a number of existing workarounds discussed above to prevent that log in your app (add a package reference, remove the environment variable, etc.).

**Comment by MHacker9404** [comment] 2018-10-09 15:47
I'm getting this issue when I try to use the EF Core Power Tools to add a model diagram to the Asp.Net Core tutorial....

**Comment by aspnet-hello** [comment] 2018-12-18 22:14
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.

**Closed by aspnet-hello** 2018-12-18 22:14 UTC
