### ISSUE TITLE
Different instance of ILoggerFactory is injected into Startup constructor than into Configure method

### ISSUE THREAD

**Issue by kosa-gyula-77** [aspnet/Hosting#1305] opened 2017-12-29 12:55 UTC
The `ILoggerFactory` instance injected into the `Startup` c'tor is _not_ the same instance as the one injected into the `Configure` method of `Startup` class. 

What I also find strange is that the `ServiceDescriptor` entry for the `ILoggerFactory` in the `IServiceCollection` argument of `ConfigureServices` has neither `ImplementationInstance` nor `ImplementationFactory` (both are `null`).

aspnet/Hosting version: 2.0.0

Is this the expected behavior?

Refer to [How to log in ConfigureServices](https://github.com/aspnet/Logging/issues/361).

Thanks.
Gyula

**Comment by Tratcher** [comment] 2017-12-29 15:33
Duplicate of https://github.com/aspnet/Hosting/issues/1150

**Closed by Tratcher** 2017-12-29 15:33 UTC
Labels: duplicate
