### ISSUE TITLE
Microsoft.AspNet.TestHost.TestServerTests.CancelAborts runs for a long time on CoreCLR on Linux

### ISSUE THREAD

**Issue by cesarbs** [aspnet/Hosting#422] opened 2015-10-19 20:43 UTC
Intermittent. I've seen it run in a timely fashion once, but then on a different build it ran for over 60 minutes (at which point the build was aborted).

**Comment by cesarbs** [comment] 2015-10-19 20:44
This affects https://github.com/aspnet/Universe/issues/304.

**Comment by muratg** [comment] 2015-10-19 21:36
@cesarbs Do you know why it hangs?  Were you able to debug?

**Comment by muratg** [comment] 2015-11-20 01:37
@JunTaoLuo Can you take a look at this one?

**Comment by muratg** [comment] 2015-11-25 18:49
@JunTaoLuo This is one of the high pri fundamentals work items that Eilon was talking about. Please have a look.

**Comment by JunTaoLuo** [comment] 2015-12-01 18:09
This no longer seems to be reproducible. I have ran the affected tests over 250 iterations without seeing any hangs on CoreCLR. I'll reenable these tests.

**Comment by JunTaoLuo** [comment] 2015-12-03 23:14
CoreCLR tests re-enabled on CI. Mono hangs tracked in #507.

**Comment by JunTaoLuo** [comment] 2015-12-10 21:57
This issue popped up on our CI again. I have been able to reproduce the issue on my own VM once I reduced resources to 1 CPU core/ 2GB RAM. We can temporarily reduce the likelihood of hangs on our CI by using agents with more resources. I suspect our TestHost is hanging due to a deadlock.

**Comment by JunTaoLuo** [comment] 2015-12-11 00:22
Confirmed this hang only reproduces on single core agents/vms unless `-parallel none` is specified for xunit. Will open an issue in Hosting to track the investigation.

Meanwhile, the temporary workaround on our CI is to use an agent with two cores. May want to add `-parallel none` for safe measure.

**Comment by muratg** [comment] 2015-12-11 03:39
Thanks @JunTaoLuo! If it turns out to be a CoreCLR issue make sure to file a bug there before closing this one.

**Comment by JunTaoLuo** [comment] 2015-12-14 18:30
Deadlock fix tested on CoreCLR using a single processor Linux VM.

**Comment by muratg** [comment] 2015-12-14 18:31
@JunTaoLuo Do we know the root cause?

**Closed by JunTaoLuo** 2015-12-14 18:30 UTC
Labels: 2 - Working, Fundamentals

**Comment by JunTaoLuo** [comment] 2015-12-14 18:41
@muratg Yes, I mentioned it in the PR. We were mixing async code in TestServer and blocking code in the test. This will cause a deadlock when we are running in single threaded environments where we can only have one active thread, for example when there is only one core. For reference in the future, linking an article that explains it better: http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html.

**Comment by muratg** [comment] 2015-12-14 18:42
Cool, thanks! :ok_hand:
