### ISSUE TITLE
Enhancement: HostingEnvironment throws DirectoryNotFoundException if wwwroot directory does not exsist

### ISSUE THREAD

**Issue by TalalTayyab** [aspnet/Hosting#133] opened 2014-12-16 22:39 UTC
Its not a bug - but suggestion to make it more Git friendly.

In Asp.Net project, by default the wwwroot folder is empty. If you check the project in Github, it will not include the wwwroot folder either because the folder is empty or (ignored due to bin directory).

If you run using Microsoft.AspNet.Hosting, no file is created inside the wwwroot folder and without a wwwroot folder it gives the directory not found exception 

An exception of type 'System.IO.DirectoryNotFoundException' occurred in Microsoft.AspNet.FileSystems.dll but was not handled in user code

If you make an empty wwwroot folder, it works. 

Proposed solution:
In the class HostingEnvironment, inside the constructor where it calls 

```C#
WebRoot = HostingUtilities.GetWebRoot(appEnvironment.ApplicationBasePath);
WebRootFileSystem = new PhysicalFileSystem(WebRoot);
```

Check if the directory exists / else create one

```C#
WebRoot = HostingUtilities.GetWebRoot(appEnvironment.ApplicationBasePath);

//Proposed change to check for directory - else create it
if (!System.IO.Directory.Exists(WebRoot))
    System.IO.Directory.CreateDirectory(WebRoot);

 WebRootFileSystem = new PhysicalFileSystem(WebRoot);
```

**Steps to reproduce**
1. Clone sample project from Git - https://github.com/TalalTayyab/HostingExceptionProject.git
2. Browse to \HostingExceptionProject\src\HostingExceptionProject
3. Restore package using kpm restore
4. Run the project using k web 
5. Exception happens
6. Create empty wwwroot folder - mkdir wwwroot
7. Run k web - works.

**Comment by Praburaj** [comment] 2015-04-08 04:56
@Tratcher 
I ran into this with many of our own samples in various repositories. I ended up adding a dummy placeholder file in the `wwwroot` to work around this. 

Empty web template included as part of VS tooling creates an empty `wwwroot`.

**Comment by Tratcher** [comment] 2015-06-15 17:29
Dupe of #233

**Closed by Tratcher** 2015-06-15 17:29 UTC
Labels: duplicate, enhancement
