### ISSUE TITLE
ApplicationStopping not called

### ISSUE THREAD

**Issue by sam-wheat** [aspnet/Hosting#921] opened 2017-01-26 01:24 UTC
https://github.com/aspnet/Hosting/issues/151

Supposedly above is fixed with:

https://github.com/aspnet/Hosting/commit/718d923c7dd1d1039fba3a5d987793226de117b7

but I still cannot get it to work.

Please see my question with code here:

http://stackoverflow.com/questions/41855340/what-happens-after-host-run

Thanks

**Comment by Tratcher** [comment] 2017-01-26 20:10
@JunTaoLuo ?

**Comment by JunTaoLuo** [comment] 2017-01-26 22:27
@sam-wheat which version of Hosting are you using? An additional issue https://github.com/aspnet/Hosting/issues/812 was fixed in 1.1.0 and 1.0.1.

**Comment by sam-wheat** [comment] 2017-01-26 22:37
"Microsoft.Extensions.Configuration.Json": "1.1.0",
		"Microsoft.AspNetCore.Mvc": "1.1.0",
		"Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
		"Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
		"Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
		"Microsoft.Extensions.Configuration.CommandLine": "1.1.0",
		"Microsoft.Extensions.Logging": "1.1.0",
		"Microsoft.Extensions.Logging.Console": "1.1.0",
		"Microsoft.Extensions.Logging.Debug": "1.1.0",
		"Microsoft.Extensions.FileProviders.Physical": "1.1.0",
		"Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
		"Microsoft.AspNetCore.Diagnostics": "1.1.0",
		"Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
		"Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
		"Microsoft.AspNetCore.StaticFiles": "1.1.0",
		"Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
		"Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
		"Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
		"Microsoft.ApplicationInsights.AspNetCore": "2.0.0-beta1",
		"Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
		"Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
		"Microsoft.VisualStudio.Web.CodeGeneration.Tools": "1.1.0-preview4-final",
		"Microsoft.VisualStudio.Web.CodeGenerators.Mvc": "1.1.0-preview4-final"
	  },
	  "tools": {
		"Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final"
	  },
	  "frameworks": {
		"netcoreapp1.1": {
		  "imports": [
			"dotnet5.6",
			"portable-net45+win8"
		  ],
		  "dependencies": {
			"Microsoft.NETCore.App": {
			  "version": "1.1.0",
			  "type": "platform"
			}
		  }
		},
		"net462": {"dependencies": {"Microsoft.NETCore.Platforms": "1.1.0"}}
	  },
	  "buildOptions": {
		"emitEntryPoint": true,
		"preserveCompilationContext": true
	  },
	  "runtimeOptions": {
		"gcServer": true
	  },

**Comment by JunTaoLuo** [comment] 2017-01-26 23:38
@sam-wheat That looks right I cannot reproduce your issue. I have a repro at https://github.com/JunTaoLuo/ApplicationStoppingRepro and the output I see is:

```
Hosting environment: Production
Content root path: C:\gh\tp\ApplicationStoppingRepro\src\ApplicationStoppingRepro\bin\Debug\netcoreapp1.0
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
Application is shutting down...
HandleStopping Completed
HandleStopped Completed
host.Run() completed
```

Which is the expected output. 

If possible, can you provide a repro that I can debug into and see what could be the problem? Also, I which version of dotnet are you using?

**Comment by leaderanalytics** [comment] 2017-01-28 18:44
Changing
    
    "Microsoft.AspNetCore.Mvc": "1.1.0",

to

    "Microsoft.AspNetCore.Mvc": "1.1.1",

did the trick.

Thanks!

**Comment by JunTaoLuo** [comment] 2017-01-28 21:12
That seems strange.

**Comment by JunTaoLuo** [comment] 2017-01-30 19:54
@sam-wheat I cannot repro your problem. It would help if you can provide more details about how you are running your app. Which OS are you running on? Are you using IIS? Are you seeing this problem on .Net Core or .NET framework?

**Comment by JunTaoLuo** [comment] 2017-01-31 00:36
I have tried .NET Core on macOS, ubuntu, and Windows and .NET Framework on Windows and have not been able to reproduce the issue. Please let me know if you can attach a repro so I can debug into this issue further.

**Comment by sam-wheat** [comment] 2017-01-31 02:50
@JunTaoLuo 
I must be crazy I cannot repro this issue again either and I worked on it for several hours before posting on StackOverflow.  I am running my laptop at work now, will try my desktop later tonight.  I put a repro together but it appears to work regardless of .MVC version.
The handlers are not triggered when the browser is closed, which causes kestrel to shut down.  This behavior is consistent regardless of .MVC version. It appears the only way to get the handlers to fire is to press Ctrl+C in the command window.


dotnet --version
1.0.0-preview3-004056

Start Visual Studio 2015 Update 3
File -> New -> Project -> ASP.Net Core Web Application (.NET Core)
Build the project
Replace project.json with file below
Replace Configure method in Startup.cs with code below
In visual studio toolbar, change  webserver to kestrel 
Run the project
Stopping/Stopped event handlers are not triggered when browser is closed.
They are triggered when Ctrl+C is pressed in kestrel window	

	{
	  "dependencies": {
		"Microsoft.Extensions.Configuration.Json": "1.1.0",
		"Microsoft.AspNetCore.Mvc": "1.1.0",
		"Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
		"Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
		"Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
		"Microsoft.Extensions.Configuration.CommandLine": "1.1.0",
		"Microsoft.Extensions.Logging": "1.1.0",
		"Microsoft.Extensions.Logging.Console": "1.1.0",
		"Microsoft.Extensions.Logging.Debug": "1.1.0",
		"Microsoft.Extensions.FileProviders.Physical": "1.1.0",
		"Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
		"Microsoft.AspNetCore.Diagnostics": "1.1.0",
		"Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
		"Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
		"Microsoft.AspNetCore.StaticFiles": "1.1.0",
		"Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
		"Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
		"Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
		"Microsoft.ApplicationInsights.AspNetCore": "2.0.0-beta1",
		"Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
		"Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
		"Microsoft.VisualStudio.Web.CodeGeneration.Tools": "1.1.0-preview4-final",
		"Microsoft.VisualStudio.Web.CodeGenerators.Mvc": "1.1.0-preview4-final"
	  },
	  "tools": {
		"Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final"
	  },
	  "frameworks": {
		"netcoreapp1.1": {
		  "imports": [
			"dotnet5.6",
			"portable-net45+win8"
		  ],
		  "dependencies": {
			"Microsoft.NETCore.App": {
			  "version": "1.1.0",
			  "type": "platform"
			}
		  }
		},
		"net462": {"dependencies": {"Microsoft.NETCore.Platforms": "1.1.0"}}
	  },
	  "buildOptions": {
		"emitEntryPoint": true,
		"preserveCompilationContext": true
	  },
	  "runtimeOptions": {
		"gcServer": true
	  } 
	}

	
	    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IApplicationLifetime applicationLifetime)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });

            applicationLifetime.ApplicationStopping.Register(() =>
            {
                Console.WriteLine("HandleStopping Completed");
            });

            applicationLifetime.ApplicationStopped.Register(() =>
            {
                Console.WriteLine("HandleStopped Completed");
            });
        }

**Comment by Tratcher** [comment] 2017-01-31 04:01
Windows 7? https://github.com/aspnet/AspNetCoreModule/issues/57

**Comment by muratg** [comment] 2017-02-03 17:49
No repro.

**Closed by muratg** 2017-02-03 17:49 UTC
