### ISSUE TITLE
Difference in behavior between UseConfiguration and ConfigureAppConfiguration

### ISSUE THREAD

**Issue by cesarbs** [aspnet/Hosting#1148] opened 2017-07-28 00:15 UTC
Ran into this while investigating https://github.com/aspnet/AzureIntegration/issues/81.

Code:

```csharp
public static void Main(string[] args)
{
    var host = new WebHostBuilder()
        .ConfigureAppConfiguration((context, config) =>
        {
            config.AddCommandLine(args);
        })
        .ConfigureLogging(factory =>
        {
            factory.SetMinimumLevel(LogLevel.Trace);
            factory.AddConsole();
        })
        .UseKestrel()
        .UseStartup<Startup>()
        .Build();

    host.Run();
}
```

Output:

```
> dotnet .\bin\Debug\netcoreapp2.0\App.dll --server.urls http://localhost:12345
...
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```

Note that it bound to the default address.

If I change the code to:

```csharp
public static void Main(string[] args)
{
    var config = new ConfigurationBuilder()
        .AddJsonFile("appsettings.json")
        .AddCommandLine(args)
        .Build();

    var host = new WebHostBuilder()
        .UseConfiguration(config)
        .ConfigureLogging(factory =>
        {
            factory.SetMinimumLevel(LogLevel.Information);
            factory.AddConsole();
        })
        .UseKestrel()
        .UseStartup<Startup>()
        .Build();

    host.Run();
}
```

It behaves as expected (binds to `http://localhost:12345`):

```
> dotnet .\bin\Debug\netcoreapp2.0\App.dll --server.urls http://localhost:12345
...
Now listening on: http://localhost:12345
Application started. Press Ctrl+C to shut down.
```

Is this by design?

**Comment by JunTaoLuo** [comment] 2017-07-28 00:42
I think the `ConfigureAppConfiguration` was intended to configure the `IConfiguration` in the application services whereas `UseConfiguration` is intended to configure the settings of the `WebHostBuilder`. Since the url address is a setting on the `WebHostBuilder` only `UseConfiguration` will work here. cc @Tratcher to make sure I'm not speaking non-sense.

**Comment by Tratcher** [comment] 2017-07-28 01:35
That about covers it. The distinction is somewhat arbitrary at this point.

**Comment by JunTaoLuo** [comment] 2017-07-28 01:51
So I guess we are happy with this behaviour and can close the issue? Or is there any possible improvement in the user experience here.

**Comment by muratg** [comment] 2017-08-08 19:47
This is by-design.

**Closed by muratg** 2017-08-08 19:47 UTC

**Comment by filipgoris** [comment] 2017-09-18 00:33
I think this is very confusing.  
Consider the following simple `apsettings.json`:  

```json
{
  "server.urls": "http://localhost:12345",
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Trace"
    }
  }
}
```

With
```c#
var config = new ConfigurationBuilder().AddJsonFile("appsettings.json")
```
and
```c#
var host = new WebHostBuilder().UseConfiguration(config)
```
`server.urls` is applied, but 
```c#
var host = new WebHostBuilder().ConfigureLogging((context, logging) =>
{
   logging.AddConfiguration(context.Configuration.GetSection("Logging"))
}
```
won't apply Log settings.  

With
```c#
var host = new WebHostBuilder()
   .configureAppConfiguration((context, config) =>
   (
      config.AddJsonFile("appsettings.json", true, true)
   })
   .configureLogging((context, logging) =>
   {
      logging.AddConfiguration(context.Configuration.GetSection("Logging"));
   ))
```
I can inject log settings, but not `server.urls`. Meaning I have to load this `appsettings.json` using both methods.

Or am I seeing this wrong?

**Comment by cesarbs** [comment] 2017-09-18 19:03
If you can read the `Logging` section from you config, there's no reason why you shouldn't be able to read `server.urls` as well (after having loaded your JSON file in `ConfigureAppConfiguration`).

**Comment by 0xorial** [comment] 2017-12-06 15:03
-2 to that design...

**Comment by RehanSaeed** [comment] 2018-05-31 15:44
I've been struggling to get Kestrel using `appsettings.json` with the correct overrides from `launchSettings.json`. 

### appsettings.json
```
{
  ...
  "Kestrel": {
    "Endpoints": {
      "Https": {
        "Url": "https://localhost:5001"
      },
      "Http": {
        "Url": "http://localhost:5000"
      }
    }
  }
}
```

### launchSettings.json
```
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:43300",
      "sslPort": 44300
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "https://localhost:44300/",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "Kestrel (dotnet run)": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "https://localhost:5001/",
      "externalUrlConfiguration": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "Kestrel (CTRL+F5 dotnet watch run)": {
      "commandName": "Executable",
      "executablePath": "dotnet",
      "workingDirectory": "$(ProjectDir)",
      "commandLineArgs": "watch run",

      // This does not work, no browser is launched.
      "launchBrowser": true,
      "launchUrl": "https://localhost:5001/",
      "externalUrlConfiguration": true,

      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

So in this scenario:

- `dotnet run` starts with ports 5000 and 5001.
- `Kestrel (dotnet run)` starts with ports 5000 and 5001.
- `Kestrel (CTRL+F5 dotnet watch run)` starts with ports 5000 and 5001.
- `IIS Express`  runs with port 43300 and 44300 (due to limitation in the ports IIS Express can use).

Use `externalUrlConfiguration` seems to stop these warnings popping up:

> warn: Microsoft.AspNetCore.Server.Kestrel[0] Overriding address(es) 'https://localhost:5001/, http://localhost:5000/'. Binding to endpoints defined in UseKestrel() instead.

Unfortunately, I've been forced to use absolute URL's instead of relative ones. Is there a better solution?

**Comment by Sigvaard** [comment] 2018-10-31 14:54
It's not clear and should be documented when to use one over another.
