### ISSUE TITLE
Cannot host ASP.NET Core Web Application (.NET Framework)

### ISSUE THREAD

**Issue by gisek** [aspnet/Hosting#791] opened 2016-06-07 23:04 UTC
Environment:
VS 2015 Community with Update 2
.NET Core RC2 SDK Preview 1
newest nuget

I create a brand new project (tested on .net 4.6 and 4.6.1) named "Test".

For:
Cannot host ASP.NET Core Web Application (.NET Core) - application **starts properly**

For:
Cannot host ASP.NET Core Web Application (.NET Framework) - application **never starts**. It just hangs with the message:

![starting_server](https://cloud.githubusercontent.com/assets/1664094/15877411/d858b6c2-2d13-11e6-8166-338594f7823a.PNG)

After I click cancel and even close VS the file bin\Debug\net46\win7-x64\Test.exe is stil used by some process. It blocks the next build. I can't delete it until I restart my machine.:
`Error      Failed to make the following project runnable: Test (.NETFramework,Version=v4.6.1) reason: The process cannot access the file 'Path\To\WebApplication2\src\Test\bin\Debug\net461\win7-x64\Test.exe' because it is being used by another process.    Test    C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets  241 Build`

`dotnet run` supposedly starts the application, but it's not listening on ports from `launchSettings.json`

Is ASP.NET Core Web Application (.NET Framework) supposed to work, or is it some kind of bug? Is there a way around it?

**Comment by gisek** [comment] 2016-06-08 08:11
@Tratcher  This is all I see after running `dotnet run`

![image](https://cloud.githubusercontent.com/assets/1664094/15887220/4d63aba0-2d61-11e6-9ee2-9e8e8f0d9beb.png)

**Comment by muratg** [comment] 2016-06-09 16:45
@gisek what happens if you run the published exe directly?

**Comment by gisek** [comment] 2016-06-09 17:49
@muratg 
For every Test.exe located in the following directories, the console just hangs with no output at all. Not sure how to check if it's listening on any port.

Path\To\Project\src\Test\bin\Debug\net461\Test.exe
Path\To\Project\src\Test\bin\Debug\net461\win7-x64\Test.exe
Path\To\Project\src\Test\bin\Debug\net461\win7-x64\publish\Test.exe

**Comment by muratg** [comment] 2016-06-09 22:01
@gisek What's your OS version? I'm not able to reproduce on my machine.

**Comment by gisek** [comment] 2016-06-09 22:35
@muratg It's Windows 10 with all the updates

**Comment by esargent** [comment] 2016-06-10 21:07
I had the same thing happening after the upgrade. (Win10 - all up to date)

Was able to follow this article http://stackoverflow.com/questions/37494297/asp-net-core-starting-the-web-server-is-taking-longer-than-expected to fix the problem, specifically the solution to remove old data protection reference.

But now VS hangs on "Debug is starting."  Even with a completely fresh new aspnetcore website (From new project template)

I realize this is probably a different issue, but if @gisek has the same thing happen after making the fix then there would be a common thread to understand and if not I hope the article helps him.

**Comment by gisek** [comment] 2016-06-11 00:09
@eerhardt I'm not sure if it's the same case. When I follow the instructions form the Stackoverflow link, a new Chrome card opens up, but it's http, not https. Also there's no popup.

![image](https://cloud.githubusercontent.com/assets/1664094/15981680/60a1d65a-2f79-11e6-87fc-5b3ce19ab0ee.png)

**Comment by gisek** [comment] 2016-06-13 21:17
A little update. For my colleague, who has the same software configuration it works fine.

**Comment by muratg** [comment] 2016-06-28 16:57
@gisek Were you ever able to get to the bottom of this?

**Comment by muratg** [comment] 2016-06-29 21:20
@gisek (Also, could you try to upgrade to RTM bits?)

**Comment by tpanthier** [comment] 2016-06-29 23:56
We have 5 developers here and 2 machines were having this issue. According to "Extensions and Updates" all updates had been applied however that was not true for the machines with issues. 

Assuming you're running an x64 system, just install all these updates and everything should just work.

1. Make sure you’re using the latest update for VS2015 (Update 3)
http://go.microsoft.com/fwlink/?LinkId=691129

2. Make sure you have the latest version of the SDK (DotNetCore.1.0.0-SDK.Preview2-x64)
https://go.microsoft.com/fwlink/?LinkID=809122

3. Make sure you have the latest version of the VS Tools (DotNetCore.1.0.0-VS2015Tools.Preview2)
https://go.microsoft.com/fwlink/?LinkId=817245

**Comment by gisek** [comment] 2016-07-09 20:32
@muratg Sorry, it took me so long to answear. I've just installed VS update 3 along with the latest DotNetCore tools. It didn't help though. :(

After that i tried to install everything @tpanthier listed, but it turned out it all had been already installed.

This locked application file seems to be the problem to me.:

> Error Failed to make the following project runnable: Test (.NETFramework,Version=v4.6.1) reason: The process cannot access the file 'Path\To\WebApplication2\src\Test\bin\Debug\net461\win7-x64\Test.exe' because it is being used by another process. Test C:\Program Files 

Which process is supposed to use it? It's not VS (restart doesn't free the file). Killing `dotnet` process doesn't help either. So far only system restart frees it.

**Comment by muratg** [comment] 2016-07-11 15:28
@gisek Did you uninstall everything else before installing the VS update, and Preview 2 tooling?

**Comment by gisek** [comment] 2016-07-11 16:26
@muratg I did not. What exactly should I uninstall? 

- VS
- DotNetCore.1.0.0-SDK.Preview2-x64
- DotNetCore.1.0.0-VS2015Tools.Preview2

Anything more?

**Comment by muratg** [comment] 2016-07-11 17:00
@gisek Those should be OK, did you have Preview1 bits (or earlier) on your machine before installing Preview 2?

**Comment by gisek** [comment] 2016-07-11 23:32
@muratg I had RC1 (which worked fine) RC2 preview1 (which didn't work), now I have RC2 preview2 (which doesn'r work)

I'll give the reinstallation a shot later this week and I'll let you know.

**Comment by marceloodiniz** [comment] 2016-07-15 01:49
I'm having the same problem: VS hangs on "Debug is starting."

Visual Studio Community 2015 (Version 14.0.25421.03 Update 3)
Project: ASP.NET Core Web Application (.NET Core)

PM> dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 
What should I do?

**Comment by gisek** [comment] 2016-07-17 21:04
@muratg Reinstalling things listed above (and uninstalling stuff from RC1) did the job. Thanks! @madskristensen good luck!

**Comment by muratg** [comment] 2016-07-19 15:37
@gisek sounds great!

**Comment by muratg** [comment] 2017-05-12 21:44
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Closed by muratg** 2017-05-12 21:44 UTC
Labels: Discussion
