### ISSUE TITLE
Some tests disabled because the dotnet CLI doesn't support x86

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Hosting#601] opened 2016-02-05 19:44 UTC
See the comments in the source code referencing this bug

**Comment by muratg** [comment] 2016-02-29 21:46
dotnet will support 32 bit for Windows soon. We should reenable these tests when that happens.

**Comment by Tratcher** [comment] 2018-05-17 16:26
Duplicate of https://github.com/aspnet/Hosting/issues/949

**Closed by Tratcher** 2018-05-17 16:26 UTC
