### ISSUE TITLE
Make IHostedService async, and run before the Server is started

### ISSUE THREAD

**Issue by anurse** [aspnet/Hosting#1085] opened 2017-05-23 19:14 UTC
In Hubbup, I'm writing an `IHostedService` to load data up from files into memory and reload them at regular intervals. There are two problems with this approach though:

1. `IHostedService.Start` is synchronous, thus I have to block the thread for any asynchronous code. Since `WebHost.StartAsync` is async, I should be able to flow continuation all the way up that call stack
2. `IHostedService.Start` is run AFTER the server is started (https://github.com/aspnet/Hosting/blob/c7bac3133f01aeea5c4e2c084159c5850440a9f8/src/Microsoft.AspNetCore.Hosting/Internal/WebHost.cs#L120). This means requests could come in before my data is loaded (in `Start`).

Since this would be a breaking change in a new 2.0 API, I'd like to nominate this for preview 2. /cc @muratg @davidfowl

**Comment by Tratcher** [comment] 2017-05-23 19:20
@glennc

**Comment by davidfowl** [comment] 2017-05-24 04:00
I think we should do this for 2.0.0 but not the part where the server order is different from the `IHostedStartup` order. I have plans to move all of the ASP.NET Core logic into an IHostedService implementation.

**Comment by anurse** [comment] 2017-05-24 16:57
I agree that 2 needs consideration given the change to move the logic in to a Hosted Service. I'd certainly like to avoid making the services order-dependent.

What about adding a third event, `Initialize` which runs before any `Start` methods run? I realize that has could descend into a full lifecycle, but it seems really useful to have a phase of startup process that runs before we start listening to ports. In my case I'm trying to load data up and I don't want to accept client connections until I've loaded that data. If I want to do that in a place that is a) injected with dependencies from the container and b) is guaranteed to run before client's are accepted, my only option is Configure, which is synchronous, and seems like the wrong place for this.

**Comment by muratg** [comment] 2017-05-24 18:15
Assigning to @JunTaoLuo

**Comment by JunTaoLuo** [comment] 2017-05-30 21:46
We resolved one part of the discussion but the design for running IHostedService before server start was never finalized. Reopening to track that discussion.

**Comment by natemcmaster** [comment] 2017-05-30 21:59
+1 to run before server starts. FYI attempting to solve https://github.com/aspnet/DataProtection/issues/233.

**Comment by anurse** [comment] 2017-06-01 19:29
> I have plans to move all of the ASP.NET Core logic into an IHostedService implementation.

What's the actual plan for this? Is it in 2.0.0? Preview 2 or later? If we're doing it at all we should do it in a preview, but if we're not doing it in 2.0, we should consider moving Hosted Services before Server.

**Comment by davidfowl** [comment] 2017-06-01 19:45
preview3

**Comment by anurse** [comment] 2017-06-01 20:16
Ok, is there an issue for it? If so, we can move discussion to there and close this, because IHostedService is now async.

**Comment by cwe1ss** [comment] 2017-06-02 07:57
+1 on running services before the server starts. I guess that many will use this for preloading stuff. If a service does not want to block startup, it can still do its work on a separate thread.

Another point: Why are [Start/Stop exceptions swallowed](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/HostedServiceExecutor.cs#L32) right now? I guess that most services will have mandatory functionality and that the app will be broken if they don't work. 
IMO the exception should be propagated so that logic like "CaptureStartupErrors" or automatic restarts from the orchestrator (e.g. Service Fabric) could kick in. If there's a service that really wants to swallow exceptions, it could still do it in its own code.

**Comment by davidfowl** [comment] 2017-06-02 08:10
>Ok, is there an issue for it? If so, we can move discussion to there and close this, because IHostedService is now async.

https://github.com/aspnet/Hosting/issues/1099 

> +1 on running services before the server starts. I guess that many will use this for preloading stuff. If a service does not want to block startup, it can still do its work on a separate thread.

That's what IStartupFilter is for.

> Another point: Why are Start/Stop exceptions swallowed right now? I guess that most services will have mandatory functionality and that the app will be broken if they don't work.
IMO the exception should be propagated so that logic like "CaptureStartupErrors" or automatic restarts from the orchestrator (e.g. Service Fabric) could kick in. If there's a service that really wants to swallow exceptions, it could still do it in its own code.

Possibly. You may end up in an infinite loop. We could log a critical error instead. I'm not sure if we should blow up.

**Comment by cwe1ss** [comment] 2017-06-02 08:27
> That's what IStartupFilter is for.

But isn't an IHostedService a more generic thing that's independent of the platform? Let's say there was a generic "RedisCacheService" that would only depend on Microsoft.Extensions.Hosting.Abstractions and could be used in web apps and e.g a console worker app - it probably should always be started before the actual host logic.

Anyway - this problem will go away if ASP.NET is a IHostedService itself, right? Because then I would just add my service first?!

> Possibly. You may end up in an infinite loop. We could log a critical error instead. I'm not sure if we should blow up.

That would be an issue of the orchestrator. The thing with catching exceptions is that you remove the possibility of blowing up at all. The other way around supports both scenarios.

**Comment by davidfowl** [comment] 2017-06-02 08:43
> But isn't an IHostedService a more generic thing that's independent of the platform? Let's say there was a generic "RedisCacheService" that would only depend on Microsoft.Extensions.Hosting.Abstractions and could be used in web apps and e.g a console worker app - it probably should always be started before the actual host logic.

That idea is fine the problem is relying on something to run before accepting "requests". You may want to do the same before accepting data from a queue or a non http endpoint. If we think this is important enough then we should add another phase to `IHostedService`. It was discussed before but IStartupFilter is the moral equivalent in the WebHost so we stuck with that for now.

> Anyway - this problem will go away if ASP.NET is a IHostedService itself, right? Because then I would just add my service first?!

Am working on that.

> That would be an issue of the orchestrator. The thing with catching exceptions is that you remove the possibility of blowing up at all. The other way around supports both scenarios.

True, I think we can throw on startup, but not shutdown.

**Comment by cwe1ss** [comment] 2017-06-02 10:48
> True, I think we can throw on startup, but not shutdown.

Good point. Interesting scenario: What if e.g. the second service throws on startup. do you now have to call Shutdown for the first on an error?

**Comment by anurse** [comment] 2017-06-02 17:06
> Anyway - this problem will go away if ASP.NET is a IHostedService itself, right? Because then I would just add my service first?!

Are we making `IHostedService` ordered? I thought we didn't want to do that...

**Comment by JunTaoLuo** [comment] 2017-06-02 19:14
To summarize here I don't think we have anything else we want to implement here in this issue.

We won't be moving IHostedService to be before server start, anything requiring initialization before server start will be implemented in IStartupFilter. We will consider making that async in https://github.com/aspnet/Hosting/issues/1088. We can also move the discussion regarding exception handling to that issue as well.

Marking this issue as closed.

**Closed by JunTaoLuo** 2017-06-02 19:14 UTC
Labels: 2 - Working, enhancement

**Comment by anurse** [comment] 2017-06-02 19:21
To further clarify, when/if #1099 is done, the Server hosted service will be registered after all ConfigureServices delegates run, so it will have the effect of making all Hosted Services registered by the app run before the server starts.
