### ISSUE TITLE
Missing dependencies when publishing net46 to Azure

### ISSUE THREAD

**Issue by hultqvist** [aspnet/Hosting#801] opened 2016-06-17 09:49 UTC
**Steps to reproduce**

Create a new dotnet core WebApplication project in Visual Studio 2015.

Modify project.json to only target `net46`:
```
  "frameworks": {
    "net46": { }
  },
```

**Result**

Locally the project worked both in IIS Express and stand-alone.

Then I published it to a web app in Azure, the result was

> The specified CGI application encountered an error and the server terminated the process

When logging was activated two exceptions was found.

First one about missing assembly `System.IO.FileSystem.Watcher`, when that was addressed the message below was logged.

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, PhysicalFilesWatcher physicalFilesWatcher)
   at Microsoft.AspNetCore.Hosting.Internal.HostingEnvironmentExtensions.Initialize(IHostingEnvironment hostingEnvironment, String applicationName, String contentRootPath, WebHostOptions options)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at WebApplication1.Program.Main(String[] args) in C:\Users\peter\DoltWindows\Documents\Visual Studio 2015\Projects\WebApplication1\src\WebApplication1\Program.cs:line 14

```

**Workaround**

After adding dependencies to the two missing files in project.json the published project worked in Azure.

```
  "dependencies": {
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "System.IO.FileSystem.Watcher": "4.0.0-rc2-24027",
    "System.IO.FileSystem": "4.0.1-rc2-24027"
  },

```

**Comment by Tratcher** [comment] 2016-06-17 16:42
@anurse can you take a look?

**Comment by anurse** [comment] 2016-06-17 18:01
@Tratcher I'll try and take a quick look but I'm a bit tight on available bandwidth right now :).

@hultqvist Would you be able to grab your full `project.lock.json` file from *before* applying the workaround and post it (to a Gist or something)? Basically if you just revert your workaround, restore, verify it's still broken and then send the lock file that would help immensely :)

**Comment by hultqvist** [comment] 2016-06-18 13:04
@anurse Here you go
https://github.com/hultqvist/aspnet-issue-801/commits/master

**Comment by charles-smith** [comment] 2016-06-19 23:31
I can confirm the same issue here.

**Comment by davidfowl** [comment] 2016-06-20 00:14
> Create a new dotnet core WebApplication project in Visual Studio 2015.

What exactly did you pick? There's 2 options .NET Core and .NET Framework.

**Comment by charles-smith** [comment] 2016-06-20 00:16
I did .NET Core, but ended up targeting net46 since I decided to use SendGrid.

**Comment by davidfowl** [comment] 2016-06-20 00:16
Can you try the repro steps choosing .NET Framework instead of .NET Core? The template is slightly different.

**Comment by charles-smith** [comment] 2016-06-20 00:23
It looks like it doesn't have a project.json file, so it'd really defeat the purpose.

**Comment by anurse** [comment] 2016-06-20 19:00
@charles-smith The template for an "ASP.NET Core app on .NET Framework" should have a `project.json`. Note that it is different from the standard "ASP.NET Web Application" template (which is ASP.NET 4.6)

**Comment by charles-smith** [comment] 2016-06-21 00:32
@anurse David's question said to not use .NET Core, did I miss something?

**Comment by Tratcher** [comment] 2016-06-21 14:59
@charles-smith just confusing naming. There's a template for Asp.Net Core on .NET Framework.

**Comment by hultqvist** [comment] 2016-06-21 17:08
I've tried the other project forms today and out of the box all net461 works.

Actually I can now remove the dependencies I added previously and it still works.

    "System.IO.FileSystem": "4.0.1-rc2-24027",
    "System.IO.FileSystem.Watcher": "4.0.0-rc2-24027"

However now the core version does not work anymore.

> The specified CGI application encountered an error and the server terminated the process.

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.CreateFileWatcher(String root)
   at Microsoft.AspNetCore.Hosting.Internal.HostingEnvironmentExtensions.Initialize(IHostingEnvironment hostingEnvironment, String applicationName, String contentRootPath, WebHostOptions options)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at WebApplicationCoreCore.Program.Main(String[] args)

```

I have no idea what to add for `System`

Might this be an Azure issue since I've not updated my tools as far as I know.

**Comment by anurse** [comment] 2016-06-21 17:29
@charles-smith Yeah, apologies for the confusion. ASP.NET Core works on both .NET Core and .NET Framework. David wanted you to try ASP.NET Core on .NET Framework (see [this diagram](http://www.hanselman.com/blog/content/binary/Windows-Live-Writer/ASP.NET-5-is-dead---Introducing-ASP.NE.0_E068/image_60140ec0-ce46-4dbf-a14f-4210eab7f42c.png) for some clarification)

**Comment by charles-smith** [comment] 2016-06-22 01:29
No problem. I finally got a chance to check it, and it worked without a hitch.

**Comment by moozzyk** [comment] 2016-06-23 00:53
@anurse - I just hit something similar after I published a project targeting net46 created from template to Antares:

I see two errors: 
```
Application startup exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection exportServices)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```
and
```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

The project.json looks like this: 

```
{
  "dependencies": {
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0"
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "net46": { }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "precompile": [ "dotnet bundle" ],
    "prepublish": [ "bower install" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

How do I troubleshoot this?

**Comment by moozzyk** [comment] 2016-06-23 16:29
@davidebbo - is it possible to turn on Fusion log on Antares? How do I trouble shoot issues like above?

**Comment by davidebbo** [comment] 2016-06-23 16:38
Before trying fusion logs, can you check whether the relevant DLLs were in fact properly deployed? If not, then it's more of a deployment than runtime issue.

Getting fusion log would probably require getting onto the VM.

**Comment by moozzyk** [comment] 2016-06-23 17:05
@davidebbo - the application seems to be deployed properly. I tried a few apps and all that target net451/net452/net46 failed this way. Apps targeting netcoreapp1.0 (standalone because 1.0.0 shared runtime is not installed) work just fine.

**Comment by davidebbo** [comment] 2016-06-23 17:07
Not sure. I guess we only tested .net core. Maybe let's wait till RTM is out and take it from there is it still repros?

**Comment by moozzyk** [comment] 2016-06-23 17:08
why does this matter if I target desktop clr?

**Comment by davidebbo** [comment] 2016-06-23 17:12
Ah you're right. I've never tried ASP.NET Core with Desktop CLR, so I know very little about it.

Scenario wise, are there reasons to use it instead of .NET Core? I seem to recall @davidfowl telling me to mostly just focus Azure Web App support on .NET Core.

Do you have a ready-to-push repo that demonstrates the issue with Desktop CLR?

**Comment by moozzyk** [comment] 2016-06-23 17:27
I can imagine that you may want to target net46 if the application is using APIs not available in .NET Core. As for the application - I just installed the latest (yetserday's) version of the tooling created a web app from the template and deployed it to an existing website I had.

**Comment by moozzyk** [comment] 2016-06-23 17:32
I think I figured this out and made it work. I manually deleted all the files I had in wwwroot and redeployed the app and it started successfully. So maybe it feels I had leftovers from previous app(s) that were picked up incorrectly. 

This might be an issue with webdeploy because I had the option to remove the files at destination checked:

![image](https://cloud.githubusercontent.com/assets/1438884/16313321/955aa29c-392d-11e6-8833-689016055db3.png)

**Comment by davidebbo** [comment] 2016-06-23 17:33
Please [share a repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue) to remove any potential difference in what we try. Make sure that it repros the issue after git pushing it to a fresh site.

**Comment by davidebbo** [comment] 2016-06-23 17:34
Just saw your comment about removing additional files. Does the issue only occur when switching from Core to Desktop? i.e. if you start with clean site and target Core, I assume all is well?

**Comment by moozzyk** [comment] 2016-06-23 17:40
I will try it again to see if I can repro this. Targeting .NET Core worked just fine.

**Comment by davidebbo** [comment] 2016-06-23 18:07
Sorry, I meant "if you start with clean site and target **Desktop**, I assume all is well?"

**Comment by moozzyk** [comment] 2016-06-23 18:14
Yes, this seems to work too. @vijayrkn tried it as well and it worked for him so I kind of expected my issue to be environmental.

**Comment by davidebbo** [comment] 2016-06-23 18:18
Ok, so it seems there is no real issue here. Just left over files causing trouble when switching stack.

**Comment by moozzyk** [comment] 2016-06-23 18:23
Yes. Looks like it. At most, webdeploy did not clean the site properly and I am going to verify this.

**Comment by davidfowl** [comment] 2016-06-27 02:59
Can we close this bug?

**Comment by davidebbo** [comment] 2016-06-27 03:44
Yep.

**Closed** 2016-06-27 03:49 UTC

**Comment by Jose-CF** [comment] 2017-06-13 07:28
Hello,
This issue still happening. My application is not .ASP but plain .NET 4.6. Same issue though. The application runs flawlessly everywhere, Windows, Linux, Mac, but when deployed to Azure that exception pops.

Any fix?

**Comment by vijayrkn** [comment] 2017-06-13 17:09
@Jose-CF - Can you please share a repro project?

>>My application is not .ASP but plain .NET 4.6
What kind of a project is it? Is it a webjob/ASP.NET on full framework?

**Comment by Jose-CF** [comment] 2017-06-16 02:49
@vijayrkn I tried with a toy example, same result. It is not ASP.NET. It is a simple .NET 4.6 assembly. 
To reproduce:
* Create a .NET 4.6 assembly, as simple as you want. 
* Install System.IO.FileSystem 4.3.0 in it. 
* Create a .NET Standard library using System.IO.FileSystem 4.3.0 package.
* Install the library in your .NET 4.6 assembly.
* Run locally works fine (Linux, Windows)
* Run in Azure fails (net46 referencing netstandard1.3: 'Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0')

I added assembly redirect to 4.0.2.0, still tries to find 4.0.1.0.

**Comment by Cephei** [comment] 2017-06-20 16:57
I just ran into this exact same issue as @Jose-CF, however, I'm not publishing to Azure; simply publishing locally (/publish). Everything works when run from Visual Studio. Published executable is broken and reports: `FileNotFoundException: Could not load file or assembly 'System.Runtime'`

Console .NET Framework 4.6.2
.NET Standard Library dll (console depends on this)

**Comment by Jose-CF** [comment] 2017-06-21 04:27
@Cephei  I think .NET Standard < 2.0 is quite abandoned... seems Microsoft only putting effort in 2.0. 2.0 even in preview has much better support for libraries dependencies.
But still... this is a big issue... cannot even use a basic library to access file system?
