### ISSUE TITLE
HttpClient of TestServer.CreateClient() can't reach URL with "%2F"

### ISSUE THREAD

**Issue by kexxxfeng** [aspnet/Hosting#1310] opened 2018-01-12 23:34 UTC
Hey:) 
.net core: 2.0
asp.net core: 2.0

I found a bug on `HttpClient` which created by `TestServer`. 

There is the demo code of server side api:
```c#
[HttpGet("{name}")]
public async Task<UserDto> Get(string name)
{
    return await _userAppService.GetUserByNameAsync(name);
}
```
I just want to get `UserDto` by `name`, but the name have `/`.

There is the intergration test:
```c#
[Fact]
public async void GetByName_TestAsync()
{
    var name = WebUtility.UrlEncode("aa/bbc");
    var response = await Client.GetAsync($"api/users/{name}"); 
    var user = await response.Content.ReadAsAsync<UserDto>();      
    user.Should().NotBeNull(); 
}
```
The `Client` was created by `TestServer`. The result of the request is 404, because `Client` decode the uri automatically. So, the request uri will be `api/users/aa/bbc`. And then, I found source code of `TestServer`.
```c#
//Microsoft.AspNetCore.TestHost  ClientHandler
req.Path = PathString.FromUriComponent(request.RequestUri);
```
This `ClientHandler` rebuild the request, and `PathString.FromUriComponent` will decode the uri, so that it can't request correct uri.

**Comment by Tratcher** [comment] 2018-01-12 23:46
%2F is a landmine, it won't work on most servers. It has long been considered an un-trusted value and un-escaped. Re-think putting that in any request path. You might have slightly more luck passing it in the query string.

**Comment by kexxxfeng** [comment] 2018-01-13 00:02
@Tratcher In my opinion, an encoded '/' is safe. The raw `HttpClient` can request the URI with `%2F`, but the `HttpClient` created by `TestServer` can't. Their behavior weren't same. That will confuse us. 

By the way, would you tell me why most servers won't work if the URI with `%2F`?

**Comment by Tratcher** [comment] 2018-01-13 00:06
It's historical from a time when servers assumed url paths mapped directly to file paths. IIS and Http.Sys for example have long treated %2F as an attempt at bypassing path based authorization and routing checks.

**Comment by kexxxfeng** [comment] 2018-01-13 00:36
@Tratcher As you say, the api hosted on IIS will return 404 if the URI with `%2F`. 

It's better to put the fragment with `%2F` into query string. 

But, the `HttpClient` created by `TestServer` do confused me a long time.

**Comment by Tratcher** [comment] 2018-01-13 01:42
Yes it's odd, but it mimics real server behaviors so I don't expect to change it.

**Comment by muratg** [comment] 2018-04-20 21:06
Thank you for your feedback. We're closing this issue as the behavior discussed seems to be by design.

**Closed by muratg** 2018-04-20 21:06 UTC
