### ISSUE TITLE
DI: Container does not dispose existing services when encountering exception in ConfigureServices()

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Hosting#1313] opened 2018-01-18 16:34 UTC
_From @helgemahrt on January 18, 2018 16:32_

I first encountered this issue in the context of Service Fabric and reported it here: [https://github.com/Azure/service-fabric-aspnetcore/issues/42](https://github.com/Azure/service-fabric-aspnetcore/issues/42) Please view this items for details. In a nutshell: When there's an exception in `ConfigureServices()` and we've added an IDisposable to the services collection, which has already been instantiated, the container doesn't dispose it correctly. 
The issue is amplified by Service Fabric, because it retries starting the web app/API without starting a new process, so the leak becomes more apparent. In our case, this lead to a high CPU hang which disabled some production level machines. However, the issue also reproduces in a standalone ASP.NET Core 2.0 web API. 
It doesn't matter whether I add an instance of my service manually to the container or whether I let the container create it, the Dispose() function is never called and the timer continues to fire after exiting ConfigureServices(), when the web app already failed to start. E.g. this also fails:
```
            services.AddSingleton<MyServiceImpl>();

            services.AddMvc();

            services.BuildServiceProvider().GetService<MyServiceImpl>();

            throw new Exception("Asdf");
```

_Copied from original issue: aspnet/Home#2800_

**Comment by davidfowl** [comment] 2018-01-26 05:18
@helgemahrt Nobody is disposing the container you built, is that what you're talking about? Why are you calling BuildServiceProvider?

**Comment by davidfowl** [comment] 2018-01-26 20:21
Ok so the problem is that if building the host throws and the host process doesn't terminate, there's no way to dispose the host (you never got a valid host because IWebHostBuilder.Build throws).

**Comment by davidfowl** [comment] 2018-01-27 02:07
In 2.1 failures in Configure no longer throw as part of building the service provider so that should be fine.  

If ConfigureServices throws though, it's a similar issue (but only for services added from the host or via the WebHostBuilder).

**Comment by davidfowl** [comment] 2018-01-27 15:02
We should consider patching this @muratg @Eilon @DamianEdwards

**Comment by Eilon** [comment] 2018-01-29 06:14
@davidfowl can you conceive of a workaround to this, for anyone affected in the meantime?

**Comment by muratg** [comment] 2018-01-30 18:11
@davidfowl Are you working on this in the preview1 branch or dev only?

**Comment by davidfowl** [comment] 2018-01-30 23:59
@Eilon @muratg There's no good workaround for 2.0.x or 1.x. It requires a bunch of . This fix is in dev only. Do we want it in preview1?

**Comment by muratg** [comment] 2018-01-31 00:53
Yeah I think we should port back to preview1.  I'm not so sure about patching or not.

**Comment by Eilon** [comment] 2018-01-31 18:29
Fine for preview1. Patching seems too extreme at this time.

**Closed** 2018-02-01 01:54 UTC
Labels: 3 - Done, bug

**Comment by khellang** [comment] 2018-02-05 08:35
We just had a user report this for Serilog; https://github.com/serilog/serilog-settings-configuration/issues/85 -- also found when hosting in Service Fabric.

I would say this should be a candidate for patching, or you need to come up with a workaround. Upgrading from 1.x to 2.x (in order to fix this) can be a non-trivial task.
