### ISSUE TITLE
Hosting a WebHostBuilder within a .NET Framework Console App does not create a libuv.dll in the build output folder

### ISSUE THREAD

**Issue by erwindevreugd** [aspnet/Hosting#1115] opened 2017-06-28 09:58 UTC
I've got a regular .NET Console app which I run as a Windows service. Within startup main I create a WebHostBuilder class:

```C#
var host = new WebHostBuilder()
    .UseUrls("http://*:9005")
    .UseKestrel()
    .UseStartup<Startup>()
    .Build();

 host.Run();
```
The starup class also is very basic:

```C#
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors();
            services.AddRouting(options => { options.LowercaseUrls = true; });
            services.AddMvc();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseCors(builder =>
                builder.AllowAnyOrigin());

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
```

Packages included within the project:

```xml
<packages>
  <package id="Libuv" version="1.9.1" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Antiforgery" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Authorization" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Cors" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Cryptography.Internal" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.DataProtection" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.DataProtection.Abstractions" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Diagnostics.Abstractions" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Hosting" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Hosting.Abstractions" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Hosting.Server.Abstractions" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Html.Abstractions" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Http" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Http.Abstractions" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Http.Extensions" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Http.Features" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.JsonPatch" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Localization" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Mvc" version="1.1.3" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Mvc.Abstractions" version="1.1.3" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Mvc.ApiExplorer" version="1.1.3" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Mvc.Core" version="1.1.3" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Mvc.Cors" version="1.1.3" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Mvc.DataAnnotations" version="1.1.3" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Mvc.Formatters.Json" version="1.1.3" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Mvc.Localization" version="1.1.3" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Mvc.Razor" version="1.1.3" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Mvc.Razor.Host" version="1.1.3" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Mvc.TagHelpers" version="1.1.3" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Mvc.ViewFeatures" version="1.1.3" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Owin" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Razor" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Razor.Runtime" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.ResponseCaching.Abstractions" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Routing" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Routing.Abstractions" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.Server.Kestrel" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.AspNetCore.WebUtilities" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.CodeAnalysis.Analyzers" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.CodeAnalysis.Common" version="1.3.0" targetFramework="net452" />
  <package id="Microsoft.CodeAnalysis.CSharp" version="1.3.0" targetFramework="net452" />
  <package id="Microsoft.CSharp" version="4.3.0" targetFramework="net452" />
  <package id="Microsoft.DotNet.PlatformAbstractions" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.Extensions.Caching.Abstractions" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.Extensions.Caching.Memory" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.Extensions.Configuration" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.Extensions.Configuration.Abstractions" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.Extensions.Configuration.EnvironmentVariables" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.Extensions.DependencyInjection" version="1.1.1" targetFramework="net452" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="1.1.1" targetFramework="net452" />
  <package id="Microsoft.Extensions.DependencyModel" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.Extensions.FileProviders.Abstractions" version="1.1.1" targetFramework="net452" />
  <package id="Microsoft.Extensions.FileProviders.Composite" version="1.1.1" targetFramework="net452" />
  <package id="Microsoft.Extensions.FileProviders.Physical" version="1.1.1" targetFramework="net452" />
  <package id="Microsoft.Extensions.FileSystemGlobbing" version="1.1.1" targetFramework="net452" />
  <package id="Microsoft.Extensions.Globalization.CultureInfoCache" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.Extensions.Localization" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.Extensions.Localization.Abstractions" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.Extensions.Logging" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.Extensions.Logging.Abstractions" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.Extensions.ObjectPool" version="1.1.1" targetFramework="net452" />
  <package id="Microsoft.Extensions.Options" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.Extensions.PlatformAbstractions" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.Extensions.Primitives" version="1.1.1" targetFramework="net452" />
  <package id="Microsoft.Extensions.WebEncoders" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.Net.Http.Headers" version="1.1.2" targetFramework="net452" />
  <package id="Microsoft.NETCore.Platforms" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.Owin" version="3.1.0" targetFramework="net452" />
  <package id="Microsoft.Owin.Cors" version="3.1.0" targetFramework="net452" />
  <package id="Microsoft.Owin.Host.HttpListener" version="3.1.0" targetFramework="net452" />
  <package id="Microsoft.Owin.Hosting" version="3.1.0" targetFramework="net452" />
  <package id="NETStandard.Library" version="1.6.1" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="net452" />
  <package id="Owin" version="1.0" targetFramework="net452" />
  <package id="System.Buffers" version="4.3.0" targetFramework="net452" />
  <package id="System.Collections" version="4.3.0" targetFramework="net452" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="net452" />
  <package id="System.Collections.Immutable" version="1.3.0" targetFramework="net452" />
  <package id="System.ComponentModel" version="4.3.0" targetFramework="net452" />
  <package id="System.Diagnostics.Contracts" version="4.3.0" targetFramework="net452" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="net452" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.3.1" targetFramework="net452" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="net452" />
  <package id="System.Diagnostics.Tracing" version="4.3.0" targetFramework="net452" />
  <package id="System.Globalization" version="4.3.0" targetFramework="net452" />
  <package id="System.IO" version="4.3.0" targetFramework="net452" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="net452" />
  <package id="System.Linq" version="4.3.0" targetFramework="net452" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="net452" />
  <package id="System.Net.Http" version="4.3.0" targetFramework="net452" />
  <package id="System.Net.Primitives" version="4.3.0" targetFramework="net452" />
  <package id="System.Numerics.Vectors" version="4.3.0" targetFramework="net452" />
  <package id="System.ObjectModel" version="4.3.0" targetFramework="net452" />
  <package id="System.Reflection" version="4.3.0" targetFramework="net452" />
  <package id="System.Reflection.Extensions" version="4.3.0" targetFramework="net452" />
  <package id="System.Reflection.Metadata" version="1.4.1" targetFramework="net452" />
  <package id="System.Reflection.Primitives" version="4.3.0" targetFramework="net452" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="net452" />
  <package id="System.Runtime" version="4.3.0" targetFramework="net452" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.3.0" targetFramework="net452" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="net452" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="net452" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net452" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="net452" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="net452" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="net452" />
  <package id="System.Text.Encodings.Web" version="4.3.1" targetFramework="net452" />
  <package id="System.Text.RegularExpressions" version="4.3.0" targetFramework="net452" />
  <package id="System.Threading" version="4.3.0" targetFramework="net452" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="net452" />
  <package id="System.Threading.Tasks.Extensions" version="4.3.0" targetFramework="net452" />
  <package id="System.Threading.Timer" version="4.3.0" targetFramework="net452" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="net452" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="net452" />
</packages>
```

Building the project does not create a libuv.dll in the build output folder. No build errors or warnings are raised. Running the application gives the following expected exception:

```
DllNotFoundException: Unable to load DLL 'libuv': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

After manually coping a version of libuv.dll to the output folder the project runs just expected.

**Comment by khellang** [comment] 2017-06-28 10:36
Basically a duplicate of the following issues:

https://github.com/aspnet/KestrelHttpServer/issues/1652
https://github.com/aspnet/KestrelHttpServer/issues/1625
https://github.com/aspnet/KestrelHttpServer/issues/1292
https://github.com/aspnet/KestrelHttpServer/issues/696

**Comment by davidfowl** [comment] 2017-06-28 14:43
You're better off using the new PackageReference support when using ASP.NET Core with existing .NET Framework projects:

![image](https://user-images.githubusercontent.com/95136/27643286-7b557b08-5bd5-11e7-9e31-b48016e7f384.png)

**Comment by khellang** [comment] 2017-06-28 14:57
> You're better off using the new PackageReference support when using ASP.NET Core with existing .NET Framework projects

Or that... if everyone that will work on the project has VS2017 😉

**Comment by erwindevreugd** [comment] 2017-06-28 16:10
Thanks guys for the workarounds. I'm sure one of them will work for me.
Sorry for the duplicate issue, I did search the Hosting repo but not the rest of asp.

**Comment by barnstee** [comment] 2017-07-04 14:09
Please let me knoe once this is fixed so I can reenable my code.

**Comment by halter73** [comment] 2017-08-01 18:24
@barnstee The fix for this issue is to use the PackageReference "package management format." It's unfortunate that this doesn't work with pre-2017 versions of VS, but I don't know of any other planned fixes.

**Closed** 2017-08-06 20:00 UTC

**Comment by skorunka** [comment] 2017-09-05 10:40
Unfortunately switching to "PackageReference" dit not help to me. I have aps.net core console app - migrated from 1.0 to core 2.0.

**Comment by davidfowl** [comment] 2017-09-05 10:41
@skorunka can you push your project to github?

**Comment by ckarcz** [comment] 2017-10-04 14:05
@davidfowl , same as @skorunka. simply switching to PackageReference doesn't work. even if explicitly building for x86 or x64.

**Comment by nzain** [comment] 2018-02-07 15:12
Nothing special required. Create a new project (it was a WPF app for me), add
```xml
<PackageReference Include="Libuv">
  <Version>1.10.0</Version>
</PackageReference>
```
and check the output - `libuv.dll` won't be copied.

Changing from `AnyCpu` to an explicit architecture (e.g. x86) will resolve the issue.

It is possible to create `AnyCpu` c# libraries that load either x86 or x64 native dlls during runtime. I realized this with [Fody.Costura](https://github.com/Fody/Costura#unmanaged32assemblies--unmanaged64assemblies), iirc. They support embedded dlls as resources and dynamic loading depending on the architecture.

**Comment by halter73** [comment] 2018-02-07 20:21
Yes. Kestrel does this. It uses a feature called ["runtime identifiers (RIDs) used by .NET packages to represent runtime-specific assets in NuGet packages"](https://github.com/dotnet/corefx/blob/257a149d3c3af85e3a486b3a713d3267fd591107/pkg/Microsoft.NETCore.Platforms/readme.md). You can see this in action with the [Libuv package](https://www.nuget.org/packages/Libuv/) on NuGet.org.

**Comment by nzain** [comment] 2018-02-07 21:59
@halter73 not exactly. The libuv package does not work with `AnyCpu` library because the dll-copying happens at build time. I was talking about dynamic dll loading during runtime. Regardless, specifing `x86` resolved the problem for me (dll copied at build time).

My comment was mostly for @davidfowl who seems to be interested in reproducing the issue.
