### ISSUE TITLE
Bootstrapping TestServer with TestStartup with InMemoryDatabase fails (No service for type 'Microsoft.Data.Entity.Storage.IRelationalConnection' has been registered)

### ISSUE THREAD

**Issue by stefanhendriks** [aspnet/Hosting#715] opened 2016-04-19 07:28 UTC
Perhaps I've missed something, or perhaps something is broken. I hope to find out what happens here.

I have a test class, which uses a TestFixture to bootstrap:

```
		public AccountControllerTest(TestServerFixture testServerFixture) : base(testServerFixture)
		{
		}

```

The testServerFixture looks like this:

```
public class TestServerFixture : IDisposable
    {
		public TestServer server { get; }

		public HttpClient client { get; }

	    public TestServerFixture()
	    {
			// Arrange
			var builder = TestServer.CreateBuilder()
				.UseEnvironment("Development")
				.UseStartup<TestPortalStartup>()
				.UseServices(services =>
				{
					// Change the application environment to the mvc project
					var env = new TestApplicationEnvironment();
					env.ApplicationBasePath =
						Path.GetFullPath(Path.Combine(PlatformServices.Default.Application.ApplicationBasePath, "..", "MY_APP"));
					env.ApplicationName = "MY_APP";
					//SUPER IMPORTANT: Should be the real application name, else you'll get Roslyn Compiler Errors in your views

					services.AddInstance<IApplicationEnvironment>(env);
				});

			server = new TestServer(builder);

			client = server.CreateClient();
		}

		public void Dispose()
	    {
			server.Dispose();
			client.Dispose();
	    }
    }
```

And as you can see it uses a `TestPortalStartup` which looks like this:

```
public class TestPortalStartup : Startup
    {
		private Mock<IAccountRegistrationClient> accountRegistrationClientMock;

		public TestPortalStartup(IHostingEnvironment env, IApplicationEnvironment appEnv) : base(env, appEnv)
	    {
	    }

		public override void SetUpDataBaseAndMigrations(IServiceCollection services)
		{
			services
			  .AddEntityFramework()
			  .AddInMemoryDatabase()
			  .AddDbContext<CmsDbContext> (
				options => options.UseInMemoryDatabase()
			);
		}


		public override void AddFrameworkDependencies(IServiceCollection services)
		{
		// ... not relevant
		}

	}
```

As you can see in the `SetUpDataBaseAndMigrations` we bootstrap an InMemoryDatabase and a DbContext.

I have used this construct before to test a Service that deals with the Database. (but this is isolated).

Now with an integration test I end up failing to bootstrap the test with:

```
Result StackTrace:	
at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.Data.Entity.RelationalDatabaseFacadeExtensions.GetRelationalConnection(DatabaseFacade databaseFacade)
   at Microsoft.Data.Entity.RelationalDatabaseFacadeExtensions.GetDbConnection(DatabaseFacade databaseFacade)
   at MY_APP.Portal.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in MY_APP/Startup.cs:line 175
Result Message:	
One or more errors occurred.
No service for type 'Microsoft.Data.Entity.Storage.IRelationalConnection' has been registered.
The following constructor parameters did not have matching fixture data: TestServerFixture testServerFixture
```

In case you wonder what happens at MY_APP/Startup.cs (line 175) that is:

```
				logger.LogInformation($"Using SQL Connection: {dbContext.Database.GetDbConnection().DataSource}");
```

Running with a 'normal' database (ie, not an In memory one) will PASS the test. So it looks like some dependencies/wiring is missing?

Any clues?

**Comment by stefanhendriks** [comment] 2016-04-25 11:02
Update:
Using `Sqlite` instead of `InMemory` works. 

For now this is sufficient, but it does not solve the actual problem.

For me, I want to run integration tests and run them isolated. Using Sqlite I can do this. I can get rid of the DB files and run tests again. I also don't need a separated DB instance. Other ways would  be to use a different Schema (on same DB instance).

**Comment by muratg** [comment] 2016-04-25 16:56
@divega Any idea what the issue may be?

**Comment by divega** [comment] 2016-04-25 18:11
Dupe of https://github.com/aspnet/EntityFramework/issues/5150.

**Closed by divega** 2016-04-25 18:11 UTC
