### ISSUE TITLE
Server Options not flowing with Autofac

### ISSUE THREAD

**Issue by douglaswaights** [aspnet/Hosting#785] opened 2016-06-06 15:41 UTC
Hi,

When using WebListener in conjunction with  Autofac DI container in RC2 the claims principle name always come back null.

Removing the IServiceProvider ConfigureServices(...) method and the identity name is available again...

Is this a bug or am I doing something wrong?

I've created a sample showing the issue
https://github.com/douglaswaights/weblistenerDI

Thanks
Doug

**Comment by Tratcher** [comment] 2016-06-06 16:56
I wonder if the `UseWebListener` Options object is somehow being dropped when switching to the new DI container, so the server gets started with the default options. If that's true, you should have similar issues configuring Kestrel.

**Comment by Tratcher** [comment] 2016-06-06 19:21
I was able to reproduce this with both Kestrel and WebListener. They both use the same WebHostBuilder extension pattern:
https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/WebHostBuilderKestrelExtensions.cs

They register a transient `IConfigureOptions<KestrelServerOptions>` and a singleton `services.Configure(options);`. Only the transient registration appears to make it across into the Autofac container, so any developer configured options from Main get lost. In Kestrel it's even slightly worse were KestrelServer null refs on the options in its constructor.

Not sure if Autofac needs to be smarter or if Kestrel and WebListener need to register their options differently.

**Comment by Tratcher** [comment] 2016-06-06 19:36
@halter73 No luck making both services into singletons. Can you take a look? The repro is easy:
https://github.com/douglaswaights/weblistenerDI/blob/master/src/weblistener/Startup.cs#L14-L22

**Comment by halter73** [comment] 2016-06-07 00:37
The root problem seems to be that Options relies on ordering: https://github.com/aspnet/Options/blob/c7bff7184d3a3ab4074859b3fd3d36d83c474357/test/Microsoft.Extensions.Options.Test/OptionsTest.cs#L143

[Autofac doesn't support that](http://stackoverflow.com/a/5231280/719967). I can't find a more authoritative source atm.

Turns out that the following is also broken along with more things that rely on options I'm sure.

```C#
new WebHostBuilder()
    .UseKestrel(options =>
    {
        options.UseHttps("testCert.pfx", "testPassword");
```

**Comment by davidfowl** [comment] 2016-06-07 01:51
@HaoK did we ever test this when we removed the order parameter from options? This is a pretty big break.

/cc @muratg @Eilon

**Comment by HaoK** [comment] 2016-06-07 02:27
Ugh, at the time MVC was the only one that was using the ordering overloads, and they were okay with removing that behavior.  But yes options relies on IEnumerable of the IConfigureOptions ordering which if is random means its will be impossible to tell what the expected option values will be...

**Comment by douglaswaights** [comment] 2016-06-07 14:47
Is this fixable for RTM do you think? Without ripping out autofac across our app its kinda blocking our upgrade from RC1.

Cheers

**Comment by muratg** [comment] 2016-06-07 15:57
@davidfowl @HaoK @halter73 What's a simple change we can do to fix this in RTM?

cc @Eilon

**Comment by HaoK** [comment] 2016-06-07 16:19
I'm not sure there is a simple fix. There used to be overloads that specified an int for order for options to be sorted by but those were removed a long time ago.

**Comment by HaoK** [comment] 2016-06-07 16:26
Would we be able to workaround this by removing the default IConfigureOption setups for kestrel/weblistener?  Each only appears to be stuffing either a logger factory or the application services into its options.

Can't you take those as service dependencies in the server themselves instead of hanging them off the options?  Then there would only be one configure options and less of an ordering issue. 

That would paper things over at least...

**Comment by Tratcher** [comment] 2016-06-07 17:02
@pakrym is trying to refactor the Kestrel scenarios. I'll try to refactor the WebListener ones.

**Comment by muratg** [comment] 2016-06-09 16:45
@HaoK @davidfowl @divega 

What's the latest on this?

**Comment by Tratcher** [comment] 2016-06-09 17:12
Decided not to refactor the servers as there are other broken scenarios. We considered refactoring Options, but there are non-Options scenarios broken too. Looks like we'll have to add some DI container requirements.

**Comment by muratg** [comment] 2016-06-29 21:21
@halter73 Could you file a tracking bug on the DI repo (if it doesn't already exist) and close this one?

Thanks.

**Comment by halter73** [comment] 2016-06-29 23:47
@muratg There's https://github.com/aspnet/DependencyInjection/issues/379 which involves updating DI requirements. The requirement we need to fix this issue was added by https://github.com/aspnet/DependencyInjection/pull/416.

I think the remaining work could be tracked by the current issue, but maybe we should create another GitHub issue to work with Autofac specifically to help them meet our specifications. Perhaps we even loosen or modify our specifications in a later release if that would help. What do you think?

**Comment by tillig** [comment] 2016-06-30 15:23
I would _love_ to see the specs loosened. It was pretty easy to implement `DependencyResolver` in MVC, `CommonServiceLocator`, and other simpler conforming container interfaces, but none of those had specs requiring _internal_ behavior work a specific way. It is proving to be _astoundingly_ non-trivial to meet the ordering requirement in Autofac.

**Comment by alexmg** [comment] 2016-06-30 15:27
Posted a comment on the DI repo about the issues we are having conforming to the ordering requirement.

aspnet/DependencyInjection#416 (comment)

**Comment by radams0x** [comment] 2016-06-30 17:47
Would it be possible to bring back some additional or alternative way to access the WebListener configuration besides this options parameter?

Regarding issue [#806 ](https://github.com/aspnet/Hosting/issues/806), that was actually the product of two recent changes. One is the issue described here regarding the options order not working with AutoFac. However, the only reason I needed to use the options was due to another change that removed the way I was registering the AuthenticationScheme before, which worked in beta6, but now ServerFeatures.Get<WebListener>() returns null:

```
        private static void setWinIntegratedAuth(IApplicationBuilder app)
        {                            
            var webListenerInfo = app.ServerFeatures.Get<WebListener>();
            webListenerInfo.AuthenticationManager.AuthenticationSchemes =
                    AuthenticationSchemes.Negotiate;
        }
```

**Comment by Tratcher** [comment] 2016-06-30 22:47
We don't plan to add that back, it was a pretty awkward design to start with. We're working with the autofac folks to get things fixed.

**Comment by alexmg** [comment] 2016-07-05 12:08
This has been resolved in https://github.com/autofac/Autofac/issues/755.

I would still recommend loosening the specifications to help others out. It's not a trivial issue.

**Comment by muratg** [comment] 2016-07-05 22:16
@alexmg do you have a build somewhere public that folks can test with?

**Comment by tillig** [comment] 2016-07-05 22:21
https://www.myget.org/feed/autofac/package/nuget/Autofac

**Comment by muratg** [comment] 2016-07-05 22:59
@douglaswaights Could you give it a try?  Thanks!

**Comment by muratg** [comment] 2016-07-25 21:05
https://github.com/aspnet/DependencyInjection/issues/433

Closing as dup.

**Closed by muratg** 2016-07-25 21:05 UTC
Labels: duplicate
